# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/char_library/char_library.xci
# IP: The module: 'char_library' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/char_library/char_library_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_library'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/char_library/char_library.xci
# IP: The module: 'char_library' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/char_library/char_library_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_library'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
