# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/fpga/loongson/soc_up.xdc

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/proc_sys_reset_0/proc_sys_reset_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==proc_sys_reset_0 || ORIG_REF_NAME==proc_sys_reset_0} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/stream_ctl_0/stream_ctl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stream_ctl_0 || ORIG_REF_NAME==stream_ctl_0} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_tft_0/axi_tft_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_tft_0 || ORIG_REF_NAME==axi_tft_0} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/v_frmbuf_rd_0/v_frmbuf_rd_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==v_frmbuf_rd_0 || ORIG_REF_NAME==v_frmbuf_rd_0} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_protocol_converter_0/axi_protocol_converter_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_protocol_converter_0 || ORIG_REF_NAME==axi_protocol_converter_0} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_clock_converter_0_1/axi_clock_converter_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_clock_converter_0 || ORIG_REF_NAME==axi_clock_converter_0} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_apb_bridge_connect/axi_apb_bridge_connect.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_apb_bridge_connect || ORIG_REF_NAME==axi_apb_bridge_connect} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/title_bram/title_bram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==title_bram || ORIG_REF_NAME==title_bram} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/lcd_clear_bram/lcd_clear_bram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_clear_bram || ORIG_REF_NAME==lcd_clear_bram} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/clk_wiz_1/clk_wiz_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/mig_axi_32/mig_axi_32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mig_axi_32 || ORIG_REF_NAME==mig_axi_32} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_interconnect_0/axi_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_interconnect_0 || ORIG_REF_NAME==axi_interconnect_0} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/clk_pll_33/clk_pll_33.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_pll_33 || ORIG_REF_NAME==clk_pll_33} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/dpram_512x32/dpram_512x32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dpram_512x32 || ORIG_REF_NAME==dpram_512x32} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/data_bank_ram/data_bank_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_bank_ram || ORIG_REF_NAME==data_bank_ram} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/tagv_ram/tagv_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tagv_ram || ORIG_REF_NAME==tagv_ram} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/bram_tagged/bram_tagged.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_tagged || ORIG_REF_NAME==bram_tagged} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/bram_base_predictor/bram_base_predictor.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_base_predictor || ORIG_REF_NAME==bram_base_predictor} -quiet] -quiet

# IP: C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/bram_ftb/bram_ftb.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_ftb || ORIG_REF_NAME==bram_ftb} -quiet] -quiet

# XDC: c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/data_bank_ram/data_bank_ram_ooc.xdc

# XDC: c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/tagv_ram/tagv_ram_ooc.xdc

# XDC: c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/bram_tagged/bram_tagged_ooc.xdc

# XDC: c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/bram_base_predictor/bram_base_predictor_ooc.xdc

# XDC: c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/bram_ftb/bram_ftb_ooc.xdc
