# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/synth_1/soc_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.cache/wt [current_project]
set_property parent.project_path C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/video_stream_modifier
  c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/altera_ps2
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/lcdctrl/initial_code/tp.coe
add_files C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/lcdctrl/initial_code/char_lib.coe
add_files C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/lcdctrl/initial_code/refresh1.coe
add_files C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/lcdctrl/initial_code/myHIT.coe
add_files C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/lcdctrl/initial_code/lcd_clear.coe
read_verilog {
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/config.h
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/mycpu.vh
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/APB_DEV/URT/uart_defines.h
}
set_property file_type "Verilog Header" [get_files C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/config.h]
set_property file_type "Verilog Header" [get_files C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/APB_DEV/URT/uart_defines.h]
read_verilog -library xil_defaultlib -sv {
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/pipeline_types.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/core_defines.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/bpu_defines.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/BU.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/EXE_stage.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/FU0.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/FU1.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/FU2.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/FU3.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/ID_stage.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/ISS_stage.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/RAT.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/RA_stage.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/ROB.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/alu.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/frontend_defines.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/base_predictor.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/bpu.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/lcdctrl/char_ctrl.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/lcdctrl/char_lib.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/commit.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/tlb_defines.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/core_top.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/csr.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/csr_hash.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/ctrl.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/ctrl_fifo.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/decoder.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/exe.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/frontend.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/ftb.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/ftq.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/ifu.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/inst_buffer.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/iss.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/issue_queue.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/lcdctrl/lcd_core.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/lcdctrl/axi_defines.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/lcdctrl/lcd_ctrl.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/lcdctrl/lcd_id.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/lcdctrl/lcd_init.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/lcdctrl/lcd_interface.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/lcdctrl/lcd_mux.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/lcdctrl/lcd_refresh.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/lcdctrl/lcd_types.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/lcdctrl/lcd_top.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/lcdctrl/lcd_touch_scanner.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/lfsr.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/mem.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/normal_priority_encoder.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/predecoder.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/ra.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/ras_my.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/regfile.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/req.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/tage_predictor.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/tagged_predictor.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/tlb.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/wb.sv
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/chip/socdemo.sv
}
read_verilog -library xil_defaultlib {
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/APB_DEV/apb_dev_top_with_nand.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/APB_DEV/apb_mux2.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/AMBA/axi2apb.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/axi_bridge.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/AMBA/axi_mux_syn.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/AMBA/axi_mux_syn2.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/AMBA/axi_mux_syn3.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/MAC/utility.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/MAC/bd.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/CONFREG/confreg_syn.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/MAC/csr.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/dcache.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/div.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/DMA/dma.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/MAC/dma.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/MAC/ethernet_top.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/SPI/godson_sbridge_spi.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/icache.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/MAC/mac.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/MAC/mac2axi.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/MAC/mac_axi.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/MAC/mac_top.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/MAC/maccsr2axi.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/MAC/macdata2axi.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/mul.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/APB_DEV/NAND/nand.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/APB_DEV/nand_module.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/APB_DEV_/URT/raminfr.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/MAC/rc.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/MAC/rfifo.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/MAC/rlsm.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/MAC/rstc.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/MAC/tc.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/team_addr_trans.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/MAC/tfifo.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/MAC/tlsm.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/tools.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/APB_DEV_/URT/uart_receiver.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/APB_DEV_/URT/uart_regs.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/APB_DEV_/URT/uart_rfifo.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/APB_DEV_/URT/uart_sync_flops.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/APB_DEV_/URT/uart_tfifo.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/APB_DEV/URT/uart_top.v
  C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/APB_DEV_/URT/uart_transmitter.v
}
read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/proc_sys_reset_0/proc_sys_reset_0.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/proc_sys_reset_0/proc_sys_reset_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/proc_sys_reset_0/proc_sys_reset_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/proc_sys_reset_0/proc_sys_reset_0_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/stream_ctl_0/stream_ctl_0.xci

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_tft_0/axi_tft_0.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_tft_0/axi_tft_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_tft_0/axi_tft_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_tft_0/axi_tft_0_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/v_frmbuf_rd_0/v_frmbuf_rd_0.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/v_frmbuf_rd_0/v_frmbuf_rd_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/v_frmbuf_rd_0/v_frmbuf_rd_0_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_protocol_converter_0/axi_protocol_converter_0.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_protocol_converter_0/axi_protocol_converter_0_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_clock_converter_0_1/axi_clock_converter_0.xci
set_property used_in_synthesis false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_clock_converter_0_1/axi_clock_converter_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_clock_converter_0_1/axi_clock_converter_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_clock_converter_0_1/axi_clock_converter_0_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_apb_bridge_connect/axi_apb_bridge_connect.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_apb_bridge_connect/axi_apb_bridge_connect_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/title_bram/title_bram.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/system_run.gen/sources_1/ip/title_bram/title_bram_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/lcd_clear_bram/lcd_clear_bram.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/lcd_clear_bram/lcd_clear_bram_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/mig_axi_32/mig_axi_32.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/mig_axi_32/mig_axi_32/user_design/constraints/mig_axi_32.xdc]
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/mig_axi_32/mig_axi_32/user_design/constraints/mig_axi_32_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_interconnect_0/axi_interconnect_0.xci
set_property used_in_synthesis false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_interconnect_0/axi_interconnect_0_impl_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_interconnect_0/axi_interconnect_0_impl_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_interconnect_0/axi_interconnect_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/axi_interconnect_0/axi_interconnect_0_clocks.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/clk_pll_33/clk_pll_33.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/clk_pll_33/clk_pll_33_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/clk_pll_33/clk_pll_33.xdc]
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/clk_pll_33/clk_pll_33_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/dpram_512x32/dpram_512x32.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/dpram_512x32/dpram_512x32_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/data_bank_ram/data_bank_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/data_bank_ram/data_bank_ram_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/tagv_ram/tagv_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/tagv_ram/tagv_ram_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/bram_tagged/bram_tagged.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/bram_tagged/bram_tagged_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/bram_base_predictor/bram_base_predictor.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/bram_base_predictor/bram_base_predictor_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/bram_ftb/bram_ftb.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/myCPU/IP/bram_ftb/bram_ftb_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/v_frmbuf_wr_0/v_frmbuf_wr_0.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/v_frmbuf_wr_0/v_frmbuf_wr_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/v_frmbuf_wr_0/v_frmbuf_wr_0_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/main_xbar/main_xbar.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/main_xbar/main_xbar_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/gt9147_init/gt9147_init.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/gt9147_init/gt9147_init_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/char_library/char_library.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/char_library/char_library_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/ps2_1/ps2.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/ps2_1/src/fifo_ps2_recv/fifo_ps2_recv.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/refresh1_bram/refresh1_bram.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/refresh1_bram/refresh1_bram_ooc.xdc]

read_ip -quiet C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/lcd_init_bram/lcd_init_bram.xci
set_property used_in_implementation false [get_files -all c:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/lcd_init_bram/lcd_init_bram_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/fpga/loongson/soc_up.xdc
set_property used_in_implementation false [get_files C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/fpga/loongson/soc_up.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
OPTRACE "compile_c" START { }
compile_c [get_files C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/IP/xilinx_ip/v_frmbuf_rd_0/v_frmbuf_rd_0.xci
]
OPTRACE "compile_c" END { }
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top soc_top -part xc7a200tfbg676-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_top_utilization_synth.rpt -pb soc_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
