set_property SRC_FILE_INFO {cfile:C:/Users/XF/Desktop/demo/chiplabdemo/chiplab/fpga/loongson/soc_up.xdc rfile:../../../../soc_up.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC19 [get_ports clk]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y3 [get_ports resetn]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K23 [get_ports {led[0]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J21 [get_ports {led[1]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H23 [get_ports {led[2]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J19 [get_ports {led[3]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G9 [get_ports {led[4]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J26 [get_ports {led[5]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J23 [get_ports {led[6]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J8 [get_ports {led[7]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H8 [get_ports {led[8]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G8 [get_ports {led[9]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F7 [get_ports {led[10]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A4 [get_ports {led[11]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A5 [get_ports {led[12]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A3 [get_ports {led[13]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D5 [get_ports {led[14]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H7 [get_ports {led[15]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G7 [get_ports {led_rg0[0]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F8 [get_ports {led_rg0[1]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B5 [get_ports {led_rg1[0]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D6 [get_ports {led_rg1[1]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D3 [get_ports {num_csn[7]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D25 [get_ports {num_csn[6]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D26 [get_ports {num_csn[5]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E25 [get_ports {num_csn[4]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E26 [get_ports {num_csn[3]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G25 [get_ports {num_csn[2]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G26 [get_ports {num_csn[1]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H26 [get_ports {num_csn[0]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C3 [get_ports {num_a_g[0]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E6 [get_ports {num_a_g[1]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B2 [get_ports {num_a_g[2]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B4 [get_ports {num_a_g[3]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E5 [get_ports {num_a_g[4]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D4 [get_ports {num_a_g[5]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A2 [get_ports {num_a_g[6]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC21 [get_ports {switch[7]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD24 [get_ports {switch[6]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC22 [get_ports {switch[5]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC23 [get_ports {switch[4]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB6 [get_ports {switch[3]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W6 [get_ports {switch[2]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA7 [get_ports {switch[1]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y6 [get_ports {switch[0]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8 [get_ports {btn_key_col[0]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9 [get_ports {btn_key_col[1]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y8 [get_ports {btn_key_col[2]}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports {btn_key_col[3]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports {btn_key_row[0]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W8 [get_ports {btn_key_row[1]}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y7 [get_ports {btn_key_row[2]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports {btn_key_row[3]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y5 [get_ports {btn_step[0]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6 [get_ports {btn_step[1]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P20 [get_ports SPI_CLK]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R20 [get_ports SPI_CS]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P19 [get_ports SPI_MISO]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18 [get_ports SPI_MOSI]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB21 [get_ports mtxclk_0]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA19 [get_ports mrxclk_0]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA15 [get_ports mtxen_0]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF18 [get_ports {mtxd_0[0]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE18 [get_ports {mtxd_0[1]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W15 [get_ports {mtxd_0[2]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W14 [get_ports {mtxd_0[3]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB20 [get_ports mtxerr_0]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE22 [get_ports mrxdv_0]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V1 [get_ports {mrxd_0[0]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports {mrxd_0[1]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V2 [get_ports {mrxd_0[2]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V3 [get_ports {mrxd_0[3]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports mrxerr_0]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y15 [get_ports mcoll_0]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF20 [get_ports mcrs_0]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W3 [get_ports mdc_0]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W1 [get_ports mdio_0]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE26 [get_ports phy_rstn]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F23 [get_ports UART_RX]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H19 [get_ports UART_TX]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M25 [get_ports UART_RX2]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P25 [get_ports UART_TX2]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V19 [get_ports NAND_CLE]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W20 [get_ports NAND_ALE]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA25 [get_ports NAND_RDY]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA24 [get_ports NAND_RD]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB24 [get_ports NAND_CE]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA22 [get_ports NAND_WR]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports {NAND_DATA[7]}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y20 [get_ports {NAND_DATA[6]}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y21 [get_ports {NAND_DATA[5]}]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V18 [get_ports {NAND_DATA[4]}]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U19 [get_ports {NAND_DATA[3]}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U20 [get_ports {NAND_DATA[2]}]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W21 [get_ports {NAND_DATA[1]}]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC24 [get_ports {NAND_DATA[0]}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports EJTAG_TRST]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18 [get_ports EJTAG_TCK]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K20 [get_ports EJTAG_TDI]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K22 [get_ports EJTAG_TMS]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K21 [get_ports EJTAG_TDO]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks clk_pll_i] -to [get_clocks clk_out2_clk_pll_33]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks mrxclk_0] -to [get_clocks clk_out2_clk_pll_33]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks mtxclk_0] -to [get_clocks clk_out2_clk_pll_33]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks clk_out2_clk_pll_33] -to [get_clocks clk_out1_clk_pll_33]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks clk_out1_clk_pll_33] -to [get_clocks clk_out2_clk_pll_33]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks clk_out2_clk_pll_33] -to [get_clocks mrxclk_0]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks clk_out2_clk_pll_33] -to [get_clocks mrxclk_0]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks clk_out2_clk_pll_33] -to [get_clocks mtxclk_0]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks clk_out2_clk_pll_33] -to [get_clocks mtxclk_0]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J25 IOSTANDARD LVCMOS33} [get_ports lcd_rst]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports lcd_cs]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports lcd_rs]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L8 IOSTANDARD LVCMOS33} [get_ports lcd_wr]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K8 IOSTANDARD LVCMOS33} [get_ports lcd_rd]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports lcd_bl_ctr]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H9 IOSTANDARD LVCMOS33} [get_ports {lcd_data_io[0]}]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports {lcd_data_io[1]}]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33} [get_ports {lcd_data_io[2]}]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports {lcd_data_io[3]}]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports {lcd_data_io[4]}]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {lcd_data_io[5]}]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports {lcd_data_io[6]}]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports {lcd_data_io[7]}]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVCMOS33} [get_ports {lcd_data_io[8]}]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS33} [get_ports {lcd_data_io[9]}]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports {lcd_data_io[10]}]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F22 IOSTANDARD LVCMOS33} [get_ports {lcd_data_io[11]}]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS33} [get_ports {lcd_data_io[12]}]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVCMOS33} [get_ports {lcd_data_io[13]}]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H24 IOSTANDARD LVCMOS33} [get_ports {lcd_data_io[14]}]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports {lcd_data_io[15]}]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33} [get_ports ct_int]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J24 IOSTANDARD LVCMOS33} [get_ports ct_sda]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H21 IOSTANDARD LVCMOS33} [get_ports ct_scl]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G24 IOSTANDARD LVCMOS33} [get_ports ct_rstn]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD1 IOSTANDARD LVCMOS33} [get_ports PS2_dat_tri_io]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y2 IOSTANDARD LVCMOS33} [get_ports PS2_clk_tri_io]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4 [get_ports {VGA_r[3]}]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2 [get_ports {VGA_r[2]}]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T2 [get_ports {VGA_r[1]}]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3 [get_ports {VGA_r[0]}]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R5 [get_ports {VGA_g[3]}]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports {VGA_g[2]}]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R1 [get_ports {VGA_g[1]}]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports {VGA_g[0]}]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports {VGA_b[3]}]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P1 [get_ports {VGA_b[2]}]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N1 [get_ports {VGA_b[1]}]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports {VGA_b[0]}]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U5 [get_ports VGA_hsync]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6 [get_ports VGA_vsync]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe0 [get_nets [list {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[0]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[1]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[2]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[3]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[4]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[5]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[6]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[7]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[8]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[9]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[10]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[11]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[12]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[13]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[14]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[15]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[16]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[17]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[18]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[19]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[20]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[21]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[22]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[23]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[24]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[25]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[26]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[27]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[28]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[29]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[30]} {soc/u_lcd_top/u_lcd_ctrl/addr_buffer[31]}]]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe1 [get_nets [list {soc/u_lcd_top/u_lcd_ctrl/s_arsize[0]} {soc/u_lcd_top/u_lcd_ctrl/s_arsize[1]} {soc/u_lcd_top/u_lcd_ctrl/s_arsize[2]}]]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe3 [get_nets [list {soc/u_lcd_top/u_lcd_ctrl/s_arburst[0]} {soc/u_lcd_top/u_lcd_ctrl/s_arburst[1]}]]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe4 [get_nets [list {soc/u_lcd_top/u_lcd_ctrl/s_araddr[0]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[1]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[2]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[3]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[4]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[5]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[6]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[7]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[8]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[9]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[10]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[11]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[12]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[13]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[14]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[15]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[16]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[17]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[18]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[19]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[20]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[21]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[22]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[23]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[24]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[25]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[26]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[27]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[28]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[29]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[30]} {soc/u_lcd_top/u_lcd_ctrl/s_araddr[31]}]]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe5 [get_nets [list {soc/u_lcd_top/u_lcd_ctrl/s_rdata[0]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[1]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[2]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[3]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[4]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[5]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[6]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[7]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[8]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[9]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[10]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[11]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[12]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[13]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[14]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[15]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[16]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[17]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[18]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[19]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[20]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[21]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[22]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[23]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[24]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[25]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[26]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[27]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[28]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[29]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[30]} {soc/u_lcd_top/u_lcd_ctrl/s_rdata[31]}]]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe6 [get_nets [list {soc/u_lcd_top/u_lcd_ctrl/s_rid[0]} {soc/u_lcd_top/u_lcd_ctrl/s_rid[1]} {soc/u_lcd_top/u_lcd_ctrl/s_rid[2]} {soc/u_lcd_top/u_lcd_ctrl/s_rid[3]}]]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe7 [get_nets [list {soc/u_lcd_top/u_lcd_ctrl/s_arcache[0]} {soc/u_lcd_top/u_lcd_ctrl/s_arcache[1]} {soc/u_lcd_top/u_lcd_ctrl/s_arcache[2]} {soc/u_lcd_top/u_lcd_ctrl/s_arcache[3]}]]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe8 [get_nets [list {soc/u_lcd_top/u_lcd_ctrl/s_arid[0]} {soc/u_lcd_top/u_lcd_ctrl/s_arid[1]} {soc/u_lcd_top/u_lcd_ctrl/s_arid[2]} {soc/u_lcd_top/u_lcd_ctrl/s_arid[3]}]]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe9 [get_nets [list {soc/u_lcd_top/u_lcd_ctrl/s_arlock[0]} {soc/u_lcd_top/u_lcd_ctrl/s_arlock[1]}]]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe10 [get_nets [list {soc/u_lcd_top/u_lcd_ctrl/s_arprot[0]} {soc/u_lcd_top/u_lcd_ctrl/s_arprot[1]} {soc/u_lcd_top/u_lcd_ctrl/s_arprot[2]}]]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe11 [get_nets [list soc/u_lcd_top/u_lcd_ctrl/s_arready]]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe12 [get_nets [list soc/u_lcd_top/u_lcd_ctrl/s_arvalid]]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe13 [get_nets [list soc/u_lcd_top/u_lcd_ctrl/s_rlast]]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe14 [get_nets [list soc/u_lcd_top/u_lcd_ctrl/s_rready]]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe15 [get_nets [list soc/u_lcd_top/u_lcd_ctrl/s_rvalid]]
