-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity v_frmbuf_wr_0_AXIvideo2MultiPixStream is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_axis_video_TDATA : IN STD_LOGIC_VECTOR (47 downto 0);
    s_axis_video_TVALID : IN STD_LOGIC;
    s_axis_video_TREADY : OUT STD_LOGIC;
    s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (5 downto 0);
    s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (5 downto 0);
    s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    img_din : OUT STD_LOGIC_VECTOR (47 downto 0);
    img_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    img_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    img_full_n : IN STD_LOGIC;
    img_write : OUT STD_LOGIC;
    Height_val : IN STD_LOGIC_VECTOR (11 downto 0);
    WidthIn_val : IN STD_LOGIC_VECTOR (11 downto 0);
    colorFormat_val : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of v_frmbuf_wr_0_AXIvideo2MultiPixStream is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal trunc_ln_reg_364 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_reg_unsigned_short_s_fu_243_ap_return : STD_LOGIC_VECTOR (11 downto 0);
    signal rows_reg_370 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal cmp10400_fu_251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp10400_reg_378 : STD_LOGIC_VECTOR (0 downto 0);
    signal cond_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cond_reg_383 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln306_fu_261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln306_reg_388 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln306_fu_281_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln306_reg_396 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal select_ln306_fu_303_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln306_reg_410 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_start : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_done : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_idle : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_ready : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_s_axis_video_TREADY : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_data_out : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_data_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_last_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_last_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_start : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_done : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_idle : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_ready : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_img_din : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_img_write : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_s_axis_video_TREADY : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_eol_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_eol_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_axi_data_3_out : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_axi_data_3_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_start : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_done : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_idle : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_ready : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_s_axis_video_TREADY : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_axi_data_4_out : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_axi_data_4_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_axi_last_4_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_axi_last_4_out_ap_vld : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_222_ap_return : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_reg_unsigned_short_s_fu_222_ap_ce : STD_LOGIC;
    signal ap_block_state1_ignore_call15 : BOOLEAN;
    signal grp_reg_unsigned_short_s_fu_243_ap_ce : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal sof_reg_126 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal axi_last_2_reg_138 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_start_reg : STD_LOGIC := '0';
    signal axi_data_2_fu_84 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal axi_last_4_loc_fu_92 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_88 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal i_2_fu_275_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln253_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component v_frmbuf_wr_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video_TVALID : IN STD_LOGIC;
        s_axis_video_TDATA : IN STD_LOGIC_VECTOR (47 downto 0);
        s_axis_video_TREADY : OUT STD_LOGIC;
        s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (5 downto 0);
        s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (5 downto 0);
        s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_data_out : OUT STD_LOGIC_VECTOR (47 downto 0);
        axi_data_out_ap_vld : OUT STD_LOGIC;
        axi_last_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        axi_last_out_ap_vld : OUT STD_LOGIC );
    end component;


    component v_frmbuf_wr_0_AXIvideo2MultiPixStream_Pipeline_loop_width IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video_TVALID : IN STD_LOGIC;
        img_din : OUT STD_LOGIC_VECTOR (47 downto 0);
        img_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        img_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        img_full_n : IN STD_LOGIC;
        img_write : OUT STD_LOGIC;
        sof_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_last_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_data_2 : IN STD_LOGIC_VECTOR (47 downto 0);
        trunc_ln : IN STD_LOGIC_VECTOR (10 downto 0);
        cond : IN STD_LOGIC_VECTOR (0 downto 0);
        colorFormat_val_cast : IN STD_LOGIC_VECTOR (2 downto 0);
        colorFormat_val : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video_TDATA : IN STD_LOGIC_VECTOR (47 downto 0);
        s_axis_video_TREADY : OUT STD_LOGIC;
        s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (5 downto 0);
        s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (5 downto 0);
        s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        eol_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        eol_out_ap_vld : OUT STD_LOGIC;
        axi_data_3_out : OUT STD_LOGIC_VECTOR (47 downto 0);
        axi_data_3_out_ap_vld : OUT STD_LOGIC );
    end component;


    component v_frmbuf_wr_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video_TVALID : IN STD_LOGIC;
        axi_data_3_reload : IN STD_LOGIC_VECTOR (47 downto 0);
        select_ln306 : IN STD_LOGIC_VECTOR (0 downto 0);
        eol_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDATA : IN STD_LOGIC_VECTOR (47 downto 0);
        s_axis_video_TREADY : OUT STD_LOGIC;
        s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (5 downto 0);
        s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (5 downto 0);
        s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_data_4_out : OUT STD_LOGIC_VECTOR (47 downto 0);
        axi_data_4_out_ap_vld : OUT STD_LOGIC;
        axi_last_4_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        axi_last_4_out_ap_vld : OUT STD_LOGIC );
    end component;


    component v_frmbuf_wr_0_reg_unsigned_short_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        d : IN STD_LOGIC_VECTOR (11 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (11 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;



begin
    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148 : component v_frmbuf_wr_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_start,
        ap_done => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_done,
        ap_idle => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_idle,
        ap_ready => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_ready,
        s_axis_video_TVALID => s_axis_video_TVALID,
        s_axis_video_TDATA => s_axis_video_TDATA,
        s_axis_video_TREADY => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_s_axis_video_TREADY,
        s_axis_video_TKEEP => s_axis_video_TKEEP,
        s_axis_video_TSTRB => s_axis_video_TSTRB,
        s_axis_video_TUSER => s_axis_video_TUSER,
        s_axis_video_TLAST => s_axis_video_TLAST,
        s_axis_video_TID => s_axis_video_TID,
        s_axis_video_TDEST => s_axis_video_TDEST,
        axi_data_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_data_out,
        axi_data_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_data_out_ap_vld,
        axi_last_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_last_out,
        axi_last_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_last_out_ap_vld);

    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168 : component v_frmbuf_wr_0_AXIvideo2MultiPixStream_Pipeline_loop_width
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_start,
        ap_done => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_done,
        ap_idle => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_idle,
        ap_ready => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_ready,
        s_axis_video_TVALID => s_axis_video_TVALID,
        img_din => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_img_din,
        img_num_data_valid => ap_const_lv3_0,
        img_fifo_cap => ap_const_lv3_0,
        img_full_n => img_full_n,
        img_write => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_img_write,
        sof_2 => sof_reg_126,
        axi_last_2 => axi_last_2_reg_138,
        axi_data_2 => axi_data_2_fu_84,
        trunc_ln => trunc_ln_reg_364,
        cond => cond_reg_383,
        colorFormat_val_cast => colorFormat_val,
        colorFormat_val => colorFormat_val,
        s_axis_video_TDATA => s_axis_video_TDATA,
        s_axis_video_TREADY => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_s_axis_video_TREADY,
        s_axis_video_TKEEP => s_axis_video_TKEEP,
        s_axis_video_TSTRB => s_axis_video_TSTRB,
        s_axis_video_TUSER => s_axis_video_TUSER,
        s_axis_video_TLAST => s_axis_video_TLAST,
        s_axis_video_TID => s_axis_video_TID,
        s_axis_video_TDEST => s_axis_video_TDEST,
        eol_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_eol_out,
        eol_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_eol_out_ap_vld,
        axi_data_3_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_axi_data_3_out,
        axi_data_3_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_axi_data_3_out_ap_vld);

    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199 : component v_frmbuf_wr_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_start,
        ap_done => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_done,
        ap_idle => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_idle,
        ap_ready => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_ready,
        s_axis_video_TVALID => s_axis_video_TVALID,
        axi_data_3_reload => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_axi_data_3_out,
        select_ln306 => select_ln306_reg_410,
        eol_reload => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_eol_out,
        s_axis_video_TDATA => s_axis_video_TDATA,
        s_axis_video_TREADY => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_s_axis_video_TREADY,
        s_axis_video_TKEEP => s_axis_video_TKEEP,
        s_axis_video_TSTRB => s_axis_video_TSTRB,
        s_axis_video_TUSER => s_axis_video_TUSER,
        s_axis_video_TLAST => s_axis_video_TLAST,
        s_axis_video_TID => s_axis_video_TID,
        s_axis_video_TDEST => s_axis_video_TDEST,
        axi_data_4_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_axi_data_4_out,
        axi_data_4_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_axi_data_4_out_ap_vld,
        axi_last_4_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_axi_last_4_out,
        axi_last_4_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_axi_last_4_out_ap_vld);

    grp_reg_unsigned_short_s_fu_222 : component v_frmbuf_wr_0_reg_unsigned_short_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        d => WidthIn_val,
        ap_return => grp_reg_unsigned_short_s_fu_222_ap_return,
        ap_ce => grp_reg_unsigned_short_s_fu_222_ap_ce);

    grp_reg_unsigned_short_s_fu_243 : component v_frmbuf_wr_0_reg_unsigned_short_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        d => Height_val,
        ap_return => grp_reg_unsigned_short_s_fu_243_ap_return,
        ap_ce => grp_reg_unsigned_short_s_fu_243_ap_ce);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln253_fu_270_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_ready = ap_const_logic_1)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_ready = ap_const_logic_1)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_ready = ap_const_logic_1)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    axi_data_2_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_axi_data_4_out_ap_vld = ap_const_logic_1))) then 
                axi_data_2_fu_84 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_axi_data_4_out;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_data_out_ap_vld = ap_const_logic_1))) then 
                axi_data_2_fu_84 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_data_out;
            end if; 
        end if;
    end process;

    axi_last_2_reg_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                axi_last_2_reg_138 <= axi_last_4_loc_fu_92;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                axi_last_2_reg_138 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_last_out;
            end if; 
        end if;
    end process;

    i_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_88 <= ap_const_lv12_0;
            elsif (((icmp_ln253_fu_270_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                i_fu_88 <= i_2_fu_275_p2;
            end if; 
        end if;
    end process;

    sof_reg_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                sof_reg_126 <= and_ln306_reg_396;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                sof_reg_126 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                and_ln306_reg_396 <= and_ln306_fu_281_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_axi_last_4_out_ap_vld = ap_const_logic_1))) then
                axi_last_4_loc_fu_92 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_axi_last_4_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                cmp10400_reg_378 <= cmp10400_fu_251_p2;
                cond_reg_383 <= cond_fu_256_p2;
                rows_reg_370 <= grp_reg_unsigned_short_s_fu_243_ap_return;
                xor_ln306_reg_388 <= xor_ln306_fu_261_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                select_ln306_reg_410 <= select_ln306_fu_303_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                trunc_ln_reg_364 <= grp_reg_unsigned_short_s_fu_222_ap_return(11 downto 1);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state5, grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_done, grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_done, grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state7, ap_CS_fsm_state10, icmp_ln253_fu_270_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((icmp_ln253_fu_270_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    and_ln306_fu_281_p2 <= (xor_ln306_reg_388 and sof_reg_126);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_done)
    begin
        if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_done)
    begin
        if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_done)
    begin
        if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call15_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call15 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state5, icmp_ln253_fu_270_p2)
    begin
        if (((icmp_ln253_fu_270_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, icmp_ln253_fu_270_p2)
    begin
        if (((icmp_ln253_fu_270_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    cmp10400_fu_251_p2 <= "0" when (trunc_ln_reg_364 = ap_const_lv11_0) else "1";
    cond_fu_256_p2 <= "1" when (colorFormat_val = ap_const_lv3_0) else "0";
    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_start <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_ap_start_reg;
    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_start <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_start_reg;
    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_start <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_start_reg;

    grp_reg_unsigned_short_s_fu_222_ap_ce_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state1_ignore_call15)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_boolean_0 = ap_block_state1_ignore_call15) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            grp_reg_unsigned_short_s_fu_222_ap_ce <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_s_fu_222_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_reg_unsigned_short_s_fu_243_ap_ce_assign_proc : process(ap_CS_fsm_state4, grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_done, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            grp_reg_unsigned_short_s_fu_243_ap_ce <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_s_fu_243_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    i_2_fu_275_p2 <= std_logic_vector(unsigned(i_fu_88) + unsigned(ap_const_lv12_1));
    icmp_ln253_fu_270_p2 <= "1" when (i_fu_88 = rows_reg_370) else "0";
    img_din <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_img_din;

    img_write_assign_proc : process(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_img_write, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            img_write <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_img_write;
        else 
            img_write <= ap_const_logic_0;
        end if; 
    end process;


    s_axis_video_TREADY_assign_proc : process(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_s_axis_video_TREADY, grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_s_axis_video_TREADY, grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_s_axis_video_TREADY, ap_CS_fsm_state3, ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            s_axis_video_TREADY <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_199_s_axis_video_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            s_axis_video_TREADY <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_s_axis_video_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            s_axis_video_TREADY <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_s_axis_video_TREADY;
        else 
            s_axis_video_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    select_ln306_fu_303_p3 <= 
        grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_eol_out when (cmp10400_reg_378(0) = '1') else 
        axi_last_2_reg_138;
    xor_ln306_fu_261_p2 <= (cmp10400_fu_251_p2 xor ap_const_lv1_1);
end behav;
