# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/ps2_1/ps2.xci
# IP: The module: 'ps2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/ps2_1/src/fifo_ps2_recv/fifo_ps2_recv.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_ps2_recv || ORIG_REF_NAME==fifo_ps2_recv} -quiet] -quiet

# XDC: c:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/ps2_1/src/fifo_ps2_recv/fifo_ps2_recv.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_ps2_recv || ORIG_REF_NAME==fifo_ps2_recv} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: C:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/ps2_1/ps2.xci
# IP: The module: 'ps2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/ps2_1/src/fifo_ps2_recv/fifo_ps2_recv.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_ps2_recv || ORIG_REF_NAME==fifo_ps2_recv} -quiet] -quiet

# XDC: c:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/ps2_1/src/fifo_ps2_recv/fifo_ps2_recv.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_ps2_recv || ORIG_REF_NAME==fifo_ps2_recv} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
