// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module v_frmbuf_wr_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_dout,
        img_num_data_valid,
        img_fifo_cap,
        img_empty_n,
        img_read,
        p_lcssa82100_i_i,
        p_lcssa8197_i_i,
        p_lcssa8094_i_i,
        p_lcssa7991_i_i,
        p_lcssa7888_i_i,
        p_lcssa85_i_i,
        trunc_ln1_i,
        cmp133_2_i_i,
        icmp6,
        bytePlanes_din,
        bytePlanes_num_data_valid,
        bytePlanes_fifo_cap,
        bytePlanes_full_n,
        bytePlanes_write,
        cmp133_i_i,
        icmp_ln930_i,
        cmp94_6_i_i,
        cmp94_5_i_i,
        cmp94_4_i_i,
        icmp3,
        cmp94_2_i_i,
        icmp,
        sub91_i_i,
        cmp94_i_i,
        p_out,
        p_out_ap_vld,
        p_out1,
        p_out1_ap_vld,
        p_out2,
        p_out2_ap_vld,
        p_out3,
        p_out3_ap_vld,
        p_out4,
        p_out4_ap_vld,
        p_out5,
        p_out5_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [47:0] img_dout;
input  [2:0] img_num_data_valid;
input  [2:0] img_fifo_cap;
input   img_empty_n;
output   img_read;
input  [7:0] p_lcssa82100_i_i;
input  [7:0] p_lcssa8197_i_i;
input  [7:0] p_lcssa8094_i_i;
input  [7:0] p_lcssa7991_i_i;
input  [7:0] p_lcssa7888_i_i;
input  [7:0] p_lcssa85_i_i;
input  [10:0] trunc_ln1_i;
input  [0:0] cmp133_2_i_i;
input  [0:0] icmp6;
output  [127:0] bytePlanes_din;
input  [9:0] bytePlanes_num_data_valid;
input  [9:0] bytePlanes_fifo_cap;
input   bytePlanes_full_n;
output   bytePlanes_write;
input  [0:0] cmp133_i_i;
input  [0:0] icmp_ln930_i;
input  [0:0] cmp94_6_i_i;
input  [0:0] cmp94_5_i_i;
input  [0:0] cmp94_4_i_i;
input  [0:0] icmp3;
input  [0:0] cmp94_2_i_i;
input  [0:0] icmp;
input  [10:0] sub91_i_i;
input  [0:0] cmp94_i_i;
output  [7:0] p_out;
output   p_out_ap_vld;
output  [7:0] p_out1;
output   p_out1_ap_vld;
output  [7:0] p_out2;
output   p_out2_ap_vld;
output  [7:0] p_out3;
output   p_out3_ap_vld;
output  [7:0] p_out4;
output   p_out4_ap_vld;
output  [7:0] p_out5;
output   p_out5_ap_vld;

reg ap_idle;
reg img_read;
reg[127:0] bytePlanes_din;
reg bytePlanes_write;
reg p_out_ap_vld;
reg p_out1_ap_vld;
reg p_out2_ap_vld;
reg p_out3_ap_vld;
reg p_out4_ap_vld;
reg p_out5_ap_vld;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
reg   [0:0] icmp_ln943_reg_1362;
reg   [0:0] or_ln948_1_reg_1398;
reg    ap_predicate_op83_read_state3;
reg    ap_block_state3_pp0_stage2_iter0;
reg    ap_block_pp0_stage2_subdone;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage7;
reg   [0:0] or_ln948_6_reg_1463;
reg    ap_predicate_op167_read_state8;
reg    ap_block_state8_pp0_stage7_iter0;
reg    ap_block_pp0_stage7_subdone;
reg    bytePlanes_blk_n;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5;
reg   [0:0] or_ln963_reg_1381;
wire    ap_block_pp0_stage0;
reg   [0:0] or_ln963_1_reg_1385;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg   [0:0] or_ln963_2_reg_1389;
reg   [0:0] or_ln963_2_reg_1389_pp0_iter1_reg;
reg    img_blk_n;
reg   [0:0] or_ln948_reg_1377;
wire    ap_block_pp0_stage2;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
reg   [0:0] or_ln948_2_reg_1437;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4;
reg   [0:0] or_ln948_3_reg_1446;
reg   [0:0] or_ln948_4_reg_1455;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6;
reg   [0:0] or_ln948_5_reg_1459;
wire    ap_block_pp0_stage7;
reg   [0:0] or_ln948_7_reg_1467;
reg   [7:0] empty_203_reg_279;
reg   [7:0] empty_204_reg_289;
reg   [7:0] empty_205_reg_299;
reg   [7:0] empty_206_reg_309;
reg   [7:0] empty_207_reg_319;
reg   [7:0] empty_208_reg_329;
reg   [7:0] empty_197_reg_339;
reg   [7:0] empty_198_reg_350;
reg   [7:0] empty_199_reg_361;
reg   [7:0] empty_200_reg_372;
reg   [7:0] empty_201_reg_383;
reg   [7:0] empty_202_reg_394;
reg   [7:0] empty_191_reg_405;
reg   [7:0] empty_192_reg_416;
reg   [7:0] empty_185_reg_471;
reg   [7:0] empty_186_reg_482;
reg   [7:0] empty_187_reg_493;
reg   [7:0] empty_188_reg_504;
reg   [7:0] empty_189_reg_515;
reg   [7:0] empty_190_reg_526;
reg   [7:0] empty_179_reg_537;
reg   [7:0] empty_180_reg_548;
reg   [7:0] empty_181_reg_559;
reg   [7:0] empty_182_reg_570;
reg   [7:0] empty_183_reg_581;
reg   [7:0] empty_184_reg_592;
reg   [7:0] empty_173_reg_603;
reg   [7:0] empty_174_reg_614;
reg   [7:0] empty_175_reg_625;
reg   [7:0] empty_176_reg_636;
reg    ap_predicate_op64_read_state2;
reg    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_state10_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_11001;
reg    ap_predicate_op115_read_state5;
reg    ap_block_state5_pp0_stage4_iter0;
reg    ap_block_pp0_stage4_11001;
reg    ap_block_pp0_stage2_11001;
reg    ap_predicate_op134_read_state6;
reg    ap_predicate_op143_write_state6;
reg    ap_block_state6_pp0_stage5_iter0;
reg    ap_block_pp0_stage5_11001;
reg    ap_predicate_op182_read_state9;
reg    ap_block_state9_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg    ap_predicate_op99_read_state4;
reg    ap_block_state4_pp0_stage3_iter0;
reg    ap_block_pp0_stage3_11001;
reg    ap_predicate_op152_read_state7;
reg    ap_block_state7_pp0_stage6_iter0;
reg    ap_block_pp0_stage6_11001;
reg   [0:0] icmp_read_reg_1327;
reg   [0:0] cmp94_2_i_i_read_reg_1332;
reg   [0:0] icmp3_read_reg_1337;
reg   [0:0] cmp94_4_i_i_read_reg_1342;
reg   [0:0] cmp94_5_i_i_read_reg_1347;
reg   [0:0] cmp94_6_i_i_read_reg_1352;
reg   [0:0] icmp_ln930_i_read_reg_1357;
wire   [0:0] icmp_ln943_fu_976_p2;
reg   [0:0] icmp_ln943_reg_1362_pp0_iter1_reg;
wire   [0:0] cmp92_i_i_fu_988_p2;
reg   [0:0] cmp92_i_i_reg_1366;
wire   [0:0] or_ln948_fu_994_p2;
wire   [0:0] or_ln963_fu_1000_p2;
wire   [0:0] or_ln963_1_fu_1006_p2;
wire   [0:0] or_ln963_2_fu_1012_p2;
wire   [7:0] trunc_ln949_fu_1023_p1;
wire   [0:0] or_ln948_1_fu_1027_p2;
wire   [7:0] trunc_ln949_1_fu_1049_p1;
wire   [0:0] or_ln948_2_fu_1053_p2;
wire   [7:0] trunc_ln949_2_fu_1057_p1;
wire   [0:0] or_ln948_3_fu_1061_p2;
wire   [7:0] trunc_ln949_3_fu_1065_p1;
wire   [0:0] or_ln948_4_fu_1069_p2;
wire   [0:0] or_ln948_5_fu_1073_p2;
wire   [0:0] or_ln948_6_fu_1077_p2;
wire   [0:0] or_ln948_7_fu_1081_p2;
wire   [7:0] trunc_ln949_4_fu_1085_p1;
wire   [7:0] trunc_ln949_5_fu_1126_p1;
wire   [7:0] trunc_ln949_6_fu_1130_p1;
reg    ap_block_pp0_stage7_11001;
wire   [7:0] trunc_ln949_7_fu_1134_p1;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_203_reg_279;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_204_reg_289;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_205_reg_299;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_206_reg_309;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_207_reg_319;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_208_reg_329;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_197_reg_339;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_198_reg_350;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_199_reg_361;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_200_reg_372;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_201_reg_383;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_202_reg_394;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_191_reg_405;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_192_reg_416;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_193_reg_427;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_194_reg_438;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_195_reg_449;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_196_reg_460;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_185_reg_471;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_186_reg_482;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_187_reg_493;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_188_reg_504;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_189_reg_515;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_190_reg_526;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_179_reg_537;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_180_reg_548;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_181_reg_559;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_182_reg_570;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_183_reg_581;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_184_reg_592;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_173_reg_603;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_173_reg_603;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_174_reg_614;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_174_reg_614;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_175_reg_625;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_175_reg_625;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_176_reg_636;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_176_reg_636;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_177_reg_647;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_177_reg_647;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_178_reg_658;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_178_reg_658;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_167_reg_669;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_167_reg_669;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_168_reg_679;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_168_reg_679;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_169_reg_689;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_169_reg_689;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_170_reg_699;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_170_reg_699;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_171_reg_709;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_171_reg_709;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_172_reg_719;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_172_reg_719;
reg   [7:0] ap_phi_mux_empty_161_phi_fu_732_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_161_reg_729;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_161_reg_729;
reg   [7:0] ap_phi_mux_empty_162_phi_fu_742_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_162_reg_739;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_162_reg_739;
reg   [7:0] ap_phi_mux_empty_163_phi_fu_752_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_163_reg_749;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_163_reg_749;
reg   [7:0] ap_phi_mux_empty_164_phi_fu_762_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_164_reg_759;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_164_reg_759;
reg   [7:0] ap_phi_mux_empty_165_phi_fu_772_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_165_reg_769;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_165_reg_769;
reg   [7:0] ap_phi_mux_empty_166_phi_fu_782_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_166_reg_779;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_166_reg_779;
reg   [9:0] x_fu_124;
wire   [9:0] x_2_fu_982_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_x_1;
reg   [7:0] empty_fu_128;
reg   [7:0] empty_156_fu_132;
reg   [7:0] empty_157_fu_136;
reg   [7:0] empty_158_fu_140;
reg   [7:0] empty_159_fu_144;
reg   [7:0] empty_160_fu_148;
wire   [127:0] p_s_fu_1089_p17;
reg    ap_block_pp0_stage5_01001;
wire   [127:0] p_1_fu_1138_p17;
reg    ap_block_pp0_stage0_01001;
wire   [127:0] p_0_fu_1175_p17;
reg    ap_block_pp0_stage1_01001;
wire   [10:0] zext_ln943_fu_972_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [7:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_1050;
reg    ap_condition_1054;
reg    ap_condition_1058;
reg    ap_condition_1062;
reg    ap_condition_1065;
reg    ap_condition_1068;
reg    ap_condition_1072;
reg    ap_condition_1076;
reg    ap_condition_1079;
reg    ap_condition_1082;
reg    ap_condition_539;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 x_fu_124 = 10'd0;
#0 empty_fu_128 = 8'd0;
#0 empty_156_fu_132 = 8'd0;
#0 empty_157_fu_136 = 8'd0;
#0 empty_158_fu_140 = 8'd0;
#0 empty_159_fu_144 = 8'd0;
#0 empty_160_fu_148 = 8'd0;
#0 ap_done_reg = 1'b0;
end

v_frmbuf_wr_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1054)) begin
            ap_phi_reg_pp0_iter0_empty_179_reg_537 <= ap_phi_reg_pp0_iter0_empty_185_reg_471;
        end else if ((1'b1 == ap_condition_1050)) begin
            ap_phi_reg_pp0_iter0_empty_179_reg_537 <= {{img_dout[47:40]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1054)) begin
            ap_phi_reg_pp0_iter0_empty_180_reg_548 <= ap_phi_reg_pp0_iter0_empty_186_reg_482;
        end else if ((1'b1 == ap_condition_1050)) begin
            ap_phi_reg_pp0_iter0_empty_180_reg_548 <= {{img_dout[39:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1054)) begin
            ap_phi_reg_pp0_iter0_empty_181_reg_559 <= ap_phi_reg_pp0_iter0_empty_187_reg_493;
        end else if ((1'b1 == ap_condition_1050)) begin
            ap_phi_reg_pp0_iter0_empty_181_reg_559 <= {{img_dout[31:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1054)) begin
            ap_phi_reg_pp0_iter0_empty_182_reg_570 <= ap_phi_reg_pp0_iter0_empty_188_reg_504;
        end else if ((1'b1 == ap_condition_1050)) begin
            ap_phi_reg_pp0_iter0_empty_182_reg_570 <= {{img_dout[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1054)) begin
            ap_phi_reg_pp0_iter0_empty_183_reg_581 <= ap_phi_reg_pp0_iter0_empty_189_reg_515;
        end else if ((1'b1 == ap_condition_1050)) begin
            ap_phi_reg_pp0_iter0_empty_183_reg_581 <= {{img_dout[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1054)) begin
            ap_phi_reg_pp0_iter0_empty_184_reg_592 <= ap_phi_reg_pp0_iter0_empty_190_reg_526;
        end else if ((1'b1 == ap_condition_1050)) begin
            ap_phi_reg_pp0_iter0_empty_184_reg_592 <= trunc_ln949_4_fu_1085_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1062)) begin
            ap_phi_reg_pp0_iter0_empty_185_reg_471 <= ap_phi_reg_pp0_iter0_empty_191_reg_405;
        end else if ((1'b1 == ap_condition_1058)) begin
            ap_phi_reg_pp0_iter0_empty_185_reg_471 <= {{img_dout[47:40]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1062)) begin
            ap_phi_reg_pp0_iter0_empty_186_reg_482 <= ap_phi_reg_pp0_iter0_empty_192_reg_416;
        end else if ((1'b1 == ap_condition_1058)) begin
            ap_phi_reg_pp0_iter0_empty_186_reg_482 <= {{img_dout[39:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1062)) begin
            ap_phi_reg_pp0_iter0_empty_187_reg_493 <= ap_phi_reg_pp0_iter0_empty_193_reg_427;
        end else if ((1'b1 == ap_condition_1058)) begin
            ap_phi_reg_pp0_iter0_empty_187_reg_493 <= {{img_dout[31:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1062)) begin
            ap_phi_reg_pp0_iter0_empty_188_reg_504 <= ap_phi_reg_pp0_iter0_empty_194_reg_438;
        end else if ((1'b1 == ap_condition_1058)) begin
            ap_phi_reg_pp0_iter0_empty_188_reg_504 <= {{img_dout[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1062)) begin
            ap_phi_reg_pp0_iter0_empty_189_reg_515 <= ap_phi_reg_pp0_iter0_empty_195_reg_449;
        end else if ((1'b1 == ap_condition_1058)) begin
            ap_phi_reg_pp0_iter0_empty_189_reg_515 <= {{img_dout[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1062)) begin
            ap_phi_reg_pp0_iter0_empty_190_reg_526 <= ap_phi_reg_pp0_iter0_empty_196_reg_460;
        end else if ((1'b1 == ap_condition_1058)) begin
            ap_phi_reg_pp0_iter0_empty_190_reg_526 <= trunc_ln949_3_fu_1065_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1068)) begin
            ap_phi_reg_pp0_iter0_empty_191_reg_405 <= ap_phi_reg_pp0_iter0_empty_197_reg_339;
        end else if ((1'b1 == ap_condition_1065)) begin
            ap_phi_reg_pp0_iter0_empty_191_reg_405 <= {{img_dout[47:40]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1068)) begin
            ap_phi_reg_pp0_iter0_empty_192_reg_416 <= ap_phi_reg_pp0_iter0_empty_198_reg_350;
        end else if ((1'b1 == ap_condition_1065)) begin
            ap_phi_reg_pp0_iter0_empty_192_reg_416 <= {{img_dout[39:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1068)) begin
            ap_phi_reg_pp0_iter0_empty_193_reg_427 <= ap_phi_reg_pp0_iter0_empty_199_reg_361;
        end else if ((1'b1 == ap_condition_1065)) begin
            ap_phi_reg_pp0_iter0_empty_193_reg_427 <= {{img_dout[31:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1068)) begin
            ap_phi_reg_pp0_iter0_empty_194_reg_438 <= ap_phi_reg_pp0_iter0_empty_200_reg_372;
        end else if ((1'b1 == ap_condition_1065)) begin
            ap_phi_reg_pp0_iter0_empty_194_reg_438 <= {{img_dout[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1068)) begin
            ap_phi_reg_pp0_iter0_empty_195_reg_449 <= ap_phi_reg_pp0_iter0_empty_201_reg_383;
        end else if ((1'b1 == ap_condition_1065)) begin
            ap_phi_reg_pp0_iter0_empty_195_reg_449 <= {{img_dout[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1068)) begin
            ap_phi_reg_pp0_iter0_empty_196_reg_460 <= ap_phi_reg_pp0_iter0_empty_202_reg_394;
        end else if ((1'b1 == ap_condition_1065)) begin
            ap_phi_reg_pp0_iter0_empty_196_reg_460 <= trunc_ln949_2_fu_1057_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1076)) begin
            ap_phi_reg_pp0_iter0_empty_197_reg_339 <= ap_phi_reg_pp0_iter0_empty_203_reg_279;
        end else if ((1'b1 == ap_condition_1072)) begin
            ap_phi_reg_pp0_iter0_empty_197_reg_339 <= {{img_dout[47:40]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1076)) begin
            ap_phi_reg_pp0_iter0_empty_198_reg_350 <= ap_phi_reg_pp0_iter0_empty_204_reg_289;
        end else if ((1'b1 == ap_condition_1072)) begin
            ap_phi_reg_pp0_iter0_empty_198_reg_350 <= {{img_dout[39:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1076)) begin
            ap_phi_reg_pp0_iter0_empty_199_reg_361 <= ap_phi_reg_pp0_iter0_empty_205_reg_299;
        end else if ((1'b1 == ap_condition_1072)) begin
            ap_phi_reg_pp0_iter0_empty_199_reg_361 <= {{img_dout[31:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1076)) begin
            ap_phi_reg_pp0_iter0_empty_200_reg_372 <= ap_phi_reg_pp0_iter0_empty_206_reg_309;
        end else if ((1'b1 == ap_condition_1072)) begin
            ap_phi_reg_pp0_iter0_empty_200_reg_372 <= {{img_dout[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1076)) begin
            ap_phi_reg_pp0_iter0_empty_201_reg_383 <= ap_phi_reg_pp0_iter0_empty_207_reg_319;
        end else if ((1'b1 == ap_condition_1072)) begin
            ap_phi_reg_pp0_iter0_empty_201_reg_383 <= {{img_dout[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1076)) begin
            ap_phi_reg_pp0_iter0_empty_202_reg_394 <= ap_phi_reg_pp0_iter0_empty_208_reg_329;
        end else if ((1'b1 == ap_condition_1072)) begin
            ap_phi_reg_pp0_iter0_empty_202_reg_394 <= trunc_ln949_1_fu_1049_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1082)) begin
            ap_phi_reg_pp0_iter0_empty_203_reg_279 <= empty_160_fu_148;
        end else if ((1'b1 == ap_condition_1079)) begin
            ap_phi_reg_pp0_iter0_empty_203_reg_279 <= {{img_dout[47:40]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1082)) begin
            ap_phi_reg_pp0_iter0_empty_204_reg_289 <= empty_159_fu_144;
        end else if ((1'b1 == ap_condition_1079)) begin
            ap_phi_reg_pp0_iter0_empty_204_reg_289 <= {{img_dout[39:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1082)) begin
            ap_phi_reg_pp0_iter0_empty_205_reg_299 <= empty_158_fu_140;
        end else if ((1'b1 == ap_condition_1079)) begin
            ap_phi_reg_pp0_iter0_empty_205_reg_299 <= {{img_dout[31:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1082)) begin
            ap_phi_reg_pp0_iter0_empty_206_reg_309 <= empty_157_fu_136;
        end else if ((1'b1 == ap_condition_1079)) begin
            ap_phi_reg_pp0_iter0_empty_206_reg_309 <= {{img_dout[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1082)) begin
            ap_phi_reg_pp0_iter0_empty_207_reg_319 <= empty_156_fu_132;
        end else if ((1'b1 == ap_condition_1079)) begin
            ap_phi_reg_pp0_iter0_empty_207_reg_319 <= {{img_dout[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1082)) begin
            ap_phi_reg_pp0_iter0_empty_208_reg_329 <= empty_fu_128;
        end else if ((1'b1 == ap_condition_1079)) begin
            ap_phi_reg_pp0_iter0_empty_208_reg_329 <= trunc_ln949_fu_1023_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln948_7_reg_1467 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_empty_161_reg_729 <= {{img_dout[47:40]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_empty_161_reg_729 <= ap_phi_reg_pp0_iter0_empty_161_reg_729;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln948_7_reg_1467 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_empty_162_reg_739 <= {{img_dout[39:32]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_empty_162_reg_739 <= ap_phi_reg_pp0_iter0_empty_162_reg_739;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln948_7_reg_1467 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_empty_163_reg_749 <= {{img_dout[31:24]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_empty_163_reg_749 <= ap_phi_reg_pp0_iter0_empty_163_reg_749;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln948_7_reg_1467 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_empty_164_reg_759 <= {{img_dout[23:16]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_empty_164_reg_759 <= ap_phi_reg_pp0_iter0_empty_164_reg_759;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln948_7_reg_1467 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_empty_165_reg_769 <= {{img_dout[15:8]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_empty_165_reg_769 <= ap_phi_reg_pp0_iter0_empty_165_reg_769;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln948_7_reg_1467 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_empty_166_reg_779 <= trunc_ln949_7_fu_1134_p1;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_empty_166_reg_779 <= ap_phi_reg_pp0_iter0_empty_166_reg_779;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln948_6_reg_1463 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_empty_167_reg_669 <= ap_phi_reg_pp0_iter1_empty_173_reg_603;
    end else if (((or_ln948_6_reg_1463 == 1'd1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_empty_167_reg_669 <= {{img_dout[47:40]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_empty_167_reg_669 <= ap_phi_reg_pp0_iter0_empty_167_reg_669;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln948_6_reg_1463 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_empty_168_reg_679 <= ap_phi_reg_pp0_iter1_empty_174_reg_614;
    end else if (((or_ln948_6_reg_1463 == 1'd1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_empty_168_reg_679 <= {{img_dout[39:32]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_empty_168_reg_679 <= ap_phi_reg_pp0_iter0_empty_168_reg_679;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln948_6_reg_1463 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_empty_169_reg_689 <= ap_phi_reg_pp0_iter1_empty_175_reg_625;
    end else if (((or_ln948_6_reg_1463 == 1'd1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_empty_169_reg_689 <= {{img_dout[31:24]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_empty_169_reg_689 <= ap_phi_reg_pp0_iter0_empty_169_reg_689;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln948_6_reg_1463 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_empty_170_reg_699 <= ap_phi_reg_pp0_iter1_empty_176_reg_636;
    end else if (((or_ln948_6_reg_1463 == 1'd1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_empty_170_reg_699 <= {{img_dout[23:16]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_empty_170_reg_699 <= ap_phi_reg_pp0_iter0_empty_170_reg_699;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln948_6_reg_1463 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_empty_171_reg_709 <= ap_phi_reg_pp0_iter1_empty_177_reg_647;
    end else if (((or_ln948_6_reg_1463 == 1'd1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_empty_171_reg_709 <= {{img_dout[15:8]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_empty_171_reg_709 <= ap_phi_reg_pp0_iter0_empty_171_reg_709;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln948_6_reg_1463 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_empty_172_reg_719 <= ap_phi_reg_pp0_iter1_empty_178_reg_658;
    end else if (((or_ln948_6_reg_1463 == 1'd1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_empty_172_reg_719 <= trunc_ln949_6_fu_1130_p1;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_empty_172_reg_719 <= ap_phi_reg_pp0_iter0_empty_172_reg_719;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_539)) begin
        if (((icmp_ln943_reg_1362 == 1'd1) & (or_ln948_5_reg_1459 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_empty_173_reg_603 <= ap_phi_reg_pp0_iter0_empty_179_reg_537;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_empty_173_reg_603 <= ap_phi_reg_pp0_iter0_empty_173_reg_603;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_539)) begin
        if (((icmp_ln943_reg_1362 == 1'd1) & (or_ln948_5_reg_1459 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_empty_174_reg_614 <= ap_phi_reg_pp0_iter0_empty_180_reg_548;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_empty_174_reg_614 <= ap_phi_reg_pp0_iter0_empty_174_reg_614;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_539)) begin
        if (((icmp_ln943_reg_1362 == 1'd1) & (or_ln948_5_reg_1459 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_empty_175_reg_625 <= ap_phi_reg_pp0_iter0_empty_181_reg_559;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_empty_175_reg_625 <= ap_phi_reg_pp0_iter0_empty_175_reg_625;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_539)) begin
        if (((icmp_ln943_reg_1362 == 1'd1) & (or_ln948_5_reg_1459 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_empty_176_reg_636 <= ap_phi_reg_pp0_iter0_empty_182_reg_570;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_empty_176_reg_636 <= ap_phi_reg_pp0_iter0_empty_176_reg_636;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_539)) begin
        if (((icmp_ln943_reg_1362 == 1'd1) & (or_ln948_5_reg_1459 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_empty_177_reg_647 <= ap_phi_reg_pp0_iter0_empty_183_reg_581;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_empty_177_reg_647 <= ap_phi_reg_pp0_iter0_empty_177_reg_647;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_539)) begin
        if (((icmp_ln943_reg_1362 == 1'd1) & (or_ln948_5_reg_1459 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_empty_178_reg_658 <= ap_phi_reg_pp0_iter0_empty_184_reg_592;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_empty_178_reg_658 <= ap_phi_reg_pp0_iter0_empty_178_reg_658;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_156_fu_132 <= p_lcssa7888_i_i;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        empty_156_fu_132 <= ap_phi_mux_empty_165_phi_fu_772_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_157_fu_136 <= p_lcssa7991_i_i;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        empty_157_fu_136 <= ap_phi_mux_empty_164_phi_fu_762_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_158_fu_140 <= p_lcssa8094_i_i;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        empty_158_fu_140 <= ap_phi_mux_empty_163_phi_fu_752_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_159_fu_144 <= p_lcssa8197_i_i;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        empty_159_fu_144 <= ap_phi_mux_empty_162_phi_fu_742_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_160_fu_148 <= p_lcssa82100_i_i;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        empty_160_fu_148 <= ap_phi_mux_empty_161_phi_fu_732_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_fu_128 <= p_lcssa85_i_i;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        empty_fu_128 <= ap_phi_mux_empty_166_phi_fu_782_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln943_fu_976_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_124 <= x_2_fu_982_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_124 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln948_5_reg_1459 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_phi_reg_pp0_iter0_empty_173_reg_603 <= {{img_dout[47:40]}};
        ap_phi_reg_pp0_iter0_empty_174_reg_614 <= {{img_dout[39:32]}};
        ap_phi_reg_pp0_iter0_empty_175_reg_625 <= {{img_dout[31:24]}};
        ap_phi_reg_pp0_iter0_empty_176_reg_636 <= {{img_dout[23:16]}};
        ap_phi_reg_pp0_iter0_empty_177_reg_647 <= {{img_dout[15:8]}};
        ap_phi_reg_pp0_iter0_empty_178_reg_658 <= trunc_ln949_5_fu_1126_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cmp92_i_i_reg_1366 <= cmp92_i_i_fu_988_p2;
        cmp94_2_i_i_read_reg_1332 <= cmp94_2_i_i;
        cmp94_4_i_i_read_reg_1342 <= cmp94_4_i_i;
        cmp94_5_i_i_read_reg_1347 <= cmp94_5_i_i;
        cmp94_6_i_i_read_reg_1352 <= cmp94_6_i_i;
        icmp3_read_reg_1337 <= icmp3;
        icmp_ln930_i_read_reg_1357 <= icmp_ln930_i;
        icmp_ln943_reg_1362 <= icmp_ln943_fu_976_p2;
        icmp_ln943_reg_1362_pp0_iter1_reg <= icmp_ln943_reg_1362;
        icmp_read_reg_1327 <= icmp;
        or_ln948_reg_1377 <= or_ln948_fu_994_p2;
        or_ln963_1_reg_1385 <= or_ln963_1_fu_1006_p2;
        or_ln963_2_reg_1389 <= or_ln963_2_fu_1012_p2;
        or_ln963_2_reg_1389_pp0_iter1_reg <= or_ln963_2_reg_1389;
        or_ln963_reg_1381 <= or_ln963_fu_1000_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_173_reg_603 <= ap_phi_reg_pp0_iter1_empty_173_reg_603;
        empty_174_reg_614 <= ap_phi_reg_pp0_iter1_empty_174_reg_614;
        empty_175_reg_625 <= ap_phi_reg_pp0_iter1_empty_175_reg_625;
        empty_176_reg_636 <= ap_phi_reg_pp0_iter1_empty_176_reg_636;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        empty_179_reg_537 <= ap_phi_reg_pp0_iter0_empty_179_reg_537;
        empty_180_reg_548 <= ap_phi_reg_pp0_iter0_empty_180_reg_548;
        empty_181_reg_559 <= ap_phi_reg_pp0_iter0_empty_181_reg_559;
        empty_182_reg_570 <= ap_phi_reg_pp0_iter0_empty_182_reg_570;
        empty_183_reg_581 <= ap_phi_reg_pp0_iter0_empty_183_reg_581;
        empty_184_reg_592 <= ap_phi_reg_pp0_iter0_empty_184_reg_592;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        empty_185_reg_471 <= ap_phi_reg_pp0_iter0_empty_185_reg_471;
        empty_186_reg_482 <= ap_phi_reg_pp0_iter0_empty_186_reg_482;
        empty_187_reg_493 <= ap_phi_reg_pp0_iter0_empty_187_reg_493;
        empty_188_reg_504 <= ap_phi_reg_pp0_iter0_empty_188_reg_504;
        empty_189_reg_515 <= ap_phi_reg_pp0_iter0_empty_189_reg_515;
        empty_190_reg_526 <= ap_phi_reg_pp0_iter0_empty_190_reg_526;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        empty_191_reg_405 <= ap_phi_reg_pp0_iter0_empty_191_reg_405;
        empty_192_reg_416 <= ap_phi_reg_pp0_iter0_empty_192_reg_416;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        empty_197_reg_339 <= ap_phi_reg_pp0_iter0_empty_197_reg_339;
        empty_198_reg_350 <= ap_phi_reg_pp0_iter0_empty_198_reg_350;
        empty_199_reg_361 <= ap_phi_reg_pp0_iter0_empty_199_reg_361;
        empty_200_reg_372 <= ap_phi_reg_pp0_iter0_empty_200_reg_372;
        empty_201_reg_383 <= ap_phi_reg_pp0_iter0_empty_201_reg_383;
        empty_202_reg_394 <= ap_phi_reg_pp0_iter0_empty_202_reg_394;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        empty_203_reg_279 <= ap_phi_reg_pp0_iter0_empty_203_reg_279;
        empty_204_reg_289 <= ap_phi_reg_pp0_iter0_empty_204_reg_289;
        empty_205_reg_299 <= ap_phi_reg_pp0_iter0_empty_205_reg_299;
        empty_206_reg_309 <= ap_phi_reg_pp0_iter0_empty_206_reg_309;
        empty_207_reg_319 <= ap_phi_reg_pp0_iter0_empty_207_reg_319;
        empty_208_reg_329 <= ap_phi_reg_pp0_iter0_empty_208_reg_329;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        or_ln948_1_reg_1398 <= or_ln948_1_fu_1027_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        or_ln948_2_reg_1437 <= or_ln948_2_fu_1053_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        or_ln948_3_reg_1446 <= or_ln948_3_fu_1061_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        or_ln948_4_reg_1455 <= or_ln948_4_fu_1069_p2;
        or_ln948_5_reg_1459 <= or_ln948_5_fu_1073_p2;
        or_ln948_6_reg_1463 <= or_ln948_6_fu_1077_p2;
        or_ln948_7_reg_1467 <= or_ln948_7_fu_1081_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (icmp_ln943_reg_1362 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln943_reg_1362_pp0_iter1_reg == 1'd1) & (or_ln948_7_reg_1467 == 1'd0))) begin
        ap_phi_mux_empty_161_phi_fu_732_p4 = ap_phi_reg_pp0_iter1_empty_167_reg_669;
    end else begin
        ap_phi_mux_empty_161_phi_fu_732_p4 = ap_phi_reg_pp0_iter1_empty_161_reg_729;
    end
end

always @ (*) begin
    if (((icmp_ln943_reg_1362_pp0_iter1_reg == 1'd1) & (or_ln948_7_reg_1467 == 1'd0))) begin
        ap_phi_mux_empty_162_phi_fu_742_p4 = ap_phi_reg_pp0_iter1_empty_168_reg_679;
    end else begin
        ap_phi_mux_empty_162_phi_fu_742_p4 = ap_phi_reg_pp0_iter1_empty_162_reg_739;
    end
end

always @ (*) begin
    if (((icmp_ln943_reg_1362_pp0_iter1_reg == 1'd1) & (or_ln948_7_reg_1467 == 1'd0))) begin
        ap_phi_mux_empty_163_phi_fu_752_p4 = ap_phi_reg_pp0_iter1_empty_169_reg_689;
    end else begin
        ap_phi_mux_empty_163_phi_fu_752_p4 = ap_phi_reg_pp0_iter1_empty_163_reg_749;
    end
end

always @ (*) begin
    if (((icmp_ln943_reg_1362_pp0_iter1_reg == 1'd1) & (or_ln948_7_reg_1467 == 1'd0))) begin
        ap_phi_mux_empty_164_phi_fu_762_p4 = ap_phi_reg_pp0_iter1_empty_170_reg_699;
    end else begin
        ap_phi_mux_empty_164_phi_fu_762_p4 = ap_phi_reg_pp0_iter1_empty_164_reg_759;
    end
end

always @ (*) begin
    if (((icmp_ln943_reg_1362_pp0_iter1_reg == 1'd1) & (or_ln948_7_reg_1467 == 1'd0))) begin
        ap_phi_mux_empty_165_phi_fu_772_p4 = ap_phi_reg_pp0_iter1_empty_171_reg_709;
    end else begin
        ap_phi_mux_empty_165_phi_fu_772_p4 = ap_phi_reg_pp0_iter1_empty_165_reg_769;
    end
end

always @ (*) begin
    if (((icmp_ln943_reg_1362_pp0_iter1_reg == 1'd1) & (or_ln948_7_reg_1467 == 1'd0))) begin
        ap_phi_mux_empty_166_phi_fu_782_p4 = ap_phi_reg_pp0_iter1_empty_172_reg_719;
    end else begin
        ap_phi_mux_empty_166_phi_fu_782_p4 = ap_phi_reg_pp0_iter1_empty_166_reg_779;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_x_1 = x_fu_124;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln963_2_reg_1389_pp0_iter1_reg == 1'd1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln963_1_reg_1385 == 1'd1)) | ((1'b0 == ap_block_pp0_stage5) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (or_ln963_reg_1381 == 1'd1)))) begin
        bytePlanes_blk_n = bytePlanes_full_n;
    end else begin
        bytePlanes_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln963_2_reg_1389_pp0_iter1_reg == 1'd1))) begin
        bytePlanes_din = p_0_fu_1175_p17;
    end else if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln963_1_reg_1385 == 1'd1))) begin
        bytePlanes_din = p_1_fu_1138_p17;
    end else if (((1'b0 == ap_block_pp0_stage5_01001) & (ap_predicate_op143_write_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        bytePlanes_din = p_s_fu_1089_p17;
    end else begin
        bytePlanes_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln963_1_reg_1385 == 1'd1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_predicate_op143_write_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln963_2_reg_1389_pp0_iter1_reg == 1'd1)))) begin
        bytePlanes_write = 1'b1;
    end else begin
        bytePlanes_write = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op167_read_state8 == 1'b1) & (1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln948_5_reg_1459 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage4) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln948_3_reg_1446 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (or_ln948_2_reg_1437 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2) & (ap_predicate_op83_read_state3 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln948_reg_1377 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter1 
    == 1'b1) & (or_ln948_7_reg_1467 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage5) & (icmp_ln943_reg_1362 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln948_4_reg_1455 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        img_blk_n = img_empty_n;
    end else begin
        img_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op167_read_state8 == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_predicate_op152_read_state7 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op99_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op182_read_state9 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_predicate_op134_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_predicate_op83_read_state3 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_op115_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) 
    & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op64_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        img_read = 1'b1;
    end else begin
        img_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln943_reg_1362 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out1_ap_vld = 1'b1;
    end else begin
        p_out1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln943_reg_1362 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out2_ap_vld = 1'b1;
    end else begin
        p_out2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln943_reg_1362 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out3_ap_vld = 1'b1;
    end else begin
        p_out3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln943_reg_1362 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out4_ap_vld = 1'b1;
    end else begin
        p_out4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln943_reg_1362 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out5_ap_vld = 1'b1;
    end else begin
        p_out5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln943_reg_1362 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_idle_pp0_1to1 == 1'b1) & (ap_start_int == 1'b0)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter1));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter1)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0));
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage5_iter0));
end

always @ (*) begin
    ap_block_pp0_stage5_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage5_iter0));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage5_iter0));
end

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage6_iter0));
end

always @ (*) begin
    ap_block_pp0_stage6_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage6_iter0));
end

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage7_iter0));
end

always @ (*) begin
    ap_block_pp0_stage7_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage7_iter0));
end

always @ (*) begin
    ap_block_state10_pp0_stage1_iter1 = ((or_ln963_2_reg_1389_pp0_iter1_reg == 1'd1) & (bytePlanes_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((img_empty_n == 1'b0) & (ap_predicate_op64_read_state2 == 1'b1));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0 = ((ap_predicate_op83_read_state3 == 1'b1) & (img_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0 = ((img_empty_n == 1'b0) & (ap_predicate_op99_read_state4 == 1'b1));
end

always @ (*) begin
    ap_block_state5_pp0_stage4_iter0 = ((img_empty_n == 1'b0) & (ap_predicate_op115_read_state5 == 1'b1));
end

always @ (*) begin
    ap_block_state6_pp0_stage5_iter0 = (((img_empty_n == 1'b0) & (ap_predicate_op134_read_state6 == 1'b1)) | ((ap_predicate_op143_write_state6 == 1'b1) & (bytePlanes_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state7_pp0_stage6_iter0 = ((img_empty_n == 1'b0) & (ap_predicate_op152_read_state7 == 1'b1));
end

always @ (*) begin
    ap_block_state8_pp0_stage7_iter0 = ((ap_predicate_op167_read_state8 == 1'b1) & (img_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter1 = (((img_empty_n == 1'b0) & (ap_predicate_op182_read_state9 == 1'b1)) | ((or_ln963_1_reg_1385 == 1'd1) & (bytePlanes_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_1050 = ((1'b0 == ap_block_pp0_stage5_11001) & (or_ln948_4_reg_1455 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage5));
end

always @ (*) begin
    ap_condition_1054 = ((1'b0 == ap_block_pp0_stage6_11001) & (or_ln948_4_reg_1455 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6));
end

always @ (*) begin
    ap_condition_1058 = ((1'b0 == ap_block_pp0_stage4_11001) & (or_ln948_3_reg_1446 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage4));
end

always @ (*) begin
    ap_condition_1062 = ((1'b0 == ap_block_pp0_stage5_11001) & (or_ln948_3_reg_1446 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5));
end

always @ (*) begin
    ap_condition_1065 = ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (or_ln948_2_reg_1437 == 1'd1));
end

always @ (*) begin
    ap_condition_1068 = ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (or_ln948_2_reg_1437 == 1'd0));
end

always @ (*) begin
    ap_condition_1072 = ((1'b0 == ap_block_pp0_stage2_11001) & (or_ln948_1_reg_1398 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2));
end

always @ (*) begin
    ap_condition_1076 = ((1'b0 == ap_block_pp0_stage3_11001) & (or_ln948_1_reg_1398 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3));
end

always @ (*) begin
    ap_condition_1079 = ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln948_reg_1377 == 1'd1));
end

always @ (*) begin
    ap_condition_1082 = ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (or_ln948_reg_1377 == 1'd0));
end

always @ (*) begin
    ap_condition_539 = ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_phi_reg_pp0_iter0_empty_161_reg_729 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_162_reg_739 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_163_reg_749 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_164_reg_759 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_165_reg_769 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_166_reg_779 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_167_reg_669 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_168_reg_679 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_169_reg_689 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_170_reg_699 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_171_reg_709 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_172_reg_719 = 'bx;

always @ (*) begin
    ap_predicate_op115_read_state5 = ((icmp_ln943_reg_1362 == 1'd1) & (or_ln948_3_reg_1446 == 1'd1));
end

always @ (*) begin
    ap_predicate_op134_read_state6 = ((icmp_ln943_reg_1362 == 1'd1) & (or_ln948_4_reg_1455 == 1'd1));
end

always @ (*) begin
    ap_predicate_op143_write_state6 = ((icmp_ln943_reg_1362 == 1'd1) & (or_ln963_reg_1381 == 1'd1));
end

always @ (*) begin
    ap_predicate_op152_read_state7 = ((icmp_ln943_reg_1362 == 1'd1) & (or_ln948_5_reg_1459 == 1'd1));
end

always @ (*) begin
    ap_predicate_op167_read_state8 = ((or_ln948_6_reg_1463 == 1'd1) & (icmp_ln943_reg_1362 == 1'd1));
end

always @ (*) begin
    ap_predicate_op182_read_state9 = ((icmp_ln943_reg_1362 == 1'd1) & (or_ln948_7_reg_1467 == 1'd1));
end

always @ (*) begin
    ap_predicate_op64_read_state2 = ((icmp_ln943_reg_1362 == 1'd1) & (or_ln948_reg_1377 == 1'd1));
end

always @ (*) begin
    ap_predicate_op83_read_state3 = ((or_ln948_1_reg_1398 == 1'd1) & (icmp_ln943_reg_1362 == 1'd1));
end

always @ (*) begin
    ap_predicate_op99_read_state4 = ((icmp_ln943_reg_1362 == 1'd1) & (or_ln948_2_reg_1437 == 1'd1));
end

assign cmp92_i_i_fu_988_p2 = (($signed(zext_ln943_fu_972_p1) < $signed(sub91_i_i)) ? 1'b1 : 1'b0);

assign icmp_ln943_fu_976_p2 = (($signed(zext_ln943_fu_972_p1) < $signed(trunc_ln1_i)) ? 1'b1 : 1'b0);

assign or_ln948_1_fu_1027_p2 = (icmp_read_reg_1327 | cmp92_i_i_reg_1366);

assign or_ln948_2_fu_1053_p2 = (cmp94_2_i_i_read_reg_1332 | cmp92_i_i_reg_1366);

assign or_ln948_3_fu_1061_p2 = (icmp3_read_reg_1337 | cmp92_i_i_reg_1366);

assign or_ln948_4_fu_1069_p2 = (cmp94_4_i_i_read_reg_1342 | cmp92_i_i_reg_1366);

assign or_ln948_5_fu_1073_p2 = (cmp94_5_i_i_read_reg_1347 | cmp92_i_i_reg_1366);

assign or_ln948_6_fu_1077_p2 = (cmp94_6_i_i_read_reg_1352 | cmp92_i_i_reg_1366);

assign or_ln948_7_fu_1081_p2 = (icmp_ln930_i_read_reg_1357 | cmp92_i_i_reg_1366);

assign or_ln948_fu_994_p2 = (cmp94_i_i | cmp92_i_i_fu_988_p2);

assign or_ln963_1_fu_1006_p2 = (icmp6 | cmp92_i_i_fu_988_p2);

assign or_ln963_2_fu_1012_p2 = (cmp92_i_i_fu_988_p2 | cmp133_2_i_i);

assign or_ln963_fu_1000_p2 = (cmp92_i_i_fu_988_p2 | cmp133_i_i);

assign p_0_fu_1175_p17 = {{{{{{{{{{{{{{{{ap_phi_mux_empty_161_phi_fu_732_p4}, {ap_phi_mux_empty_162_phi_fu_742_p4}}, {ap_phi_mux_empty_163_phi_fu_752_p4}}, {ap_phi_mux_empty_164_phi_fu_762_p4}}, {ap_phi_mux_empty_165_phi_fu_772_p4}}, {ap_phi_mux_empty_166_phi_fu_782_p4}}, {ap_phi_reg_pp0_iter1_empty_167_reg_669}}, {ap_phi_reg_pp0_iter1_empty_168_reg_679}}, {ap_phi_reg_pp0_iter1_empty_169_reg_689}}, {ap_phi_reg_pp0_iter1_empty_170_reg_699}}, {ap_phi_reg_pp0_iter1_empty_171_reg_709}}, {ap_phi_reg_pp0_iter1_empty_172_reg_719}}, {empty_173_reg_603}}, {empty_174_reg_614}}, {empty_175_reg_625}}, {empty_176_reg_636}};

assign p_1_fu_1138_p17 = {{{{{{{{{{{{{{{{ap_phi_reg_pp0_iter1_empty_177_reg_647}, {ap_phi_reg_pp0_iter1_empty_178_reg_658}}, {empty_179_reg_537}}, {empty_180_reg_548}}, {empty_181_reg_559}}, {empty_182_reg_570}}, {empty_183_reg_581}}, {empty_184_reg_592}}, {empty_185_reg_471}}, {empty_186_reg_482}}, {empty_187_reg_493}}, {empty_188_reg_504}}, {empty_189_reg_515}}, {empty_190_reg_526}}, {empty_191_reg_405}}, {empty_192_reg_416}};

assign p_out = empty_160_fu_148;

assign p_out1 = empty_159_fu_144;

assign p_out2 = empty_158_fu_140;

assign p_out3 = empty_157_fu_136;

assign p_out4 = empty_156_fu_132;

assign p_out5 = empty_fu_128;

assign p_s_fu_1089_p17 = {{{{{{{{{{{{{{{{ap_phi_reg_pp0_iter0_empty_193_reg_427}, {ap_phi_reg_pp0_iter0_empty_194_reg_438}}, {ap_phi_reg_pp0_iter0_empty_195_reg_449}}, {ap_phi_reg_pp0_iter0_empty_196_reg_460}}, {empty_197_reg_339}}, {empty_198_reg_350}}, {empty_199_reg_361}}, {empty_200_reg_372}}, {empty_201_reg_383}}, {empty_202_reg_394}}, {empty_203_reg_279}}, {empty_204_reg_289}}, {empty_205_reg_299}}, {empty_206_reg_309}}, {empty_207_reg_319}}, {empty_208_reg_329}};

assign trunc_ln949_1_fu_1049_p1 = img_dout[7:0];

assign trunc_ln949_2_fu_1057_p1 = img_dout[7:0];

assign trunc_ln949_3_fu_1065_p1 = img_dout[7:0];

assign trunc_ln949_4_fu_1085_p1 = img_dout[7:0];

assign trunc_ln949_5_fu_1126_p1 = img_dout[7:0];

assign trunc_ln949_6_fu_1130_p1 = img_dout[7:0];

assign trunc_ln949_7_fu_1134_p1 = img_dout[7:0];

assign trunc_ln949_fu_1023_p1 = img_dout[7:0];

assign x_2_fu_982_p2 = (ap_sig_allocacmp_x_1 + 10'd1);

assign zext_ln943_fu_972_p1 = ap_sig_allocacmp_x_1;

endmodule //v_frmbuf_wr_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1
