// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module v_frmbuf_wr_0_FrmbufWrHlsDataFlow (
        s_axis_video_TDATA,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        m_axi_mm_video_AWVALID,
        m_axi_mm_video_AWREADY,
        m_axi_mm_video_AWADDR,
        m_axi_mm_video_AWID,
        m_axi_mm_video_AWLEN,
        m_axi_mm_video_AWSIZE,
        m_axi_mm_video_AWBURST,
        m_axi_mm_video_AWLOCK,
        m_axi_mm_video_AWCACHE,
        m_axi_mm_video_AWPROT,
        m_axi_mm_video_AWQOS,
        m_axi_mm_video_AWREGION,
        m_axi_mm_video_AWUSER,
        m_axi_mm_video_WVALID,
        m_axi_mm_video_WREADY,
        m_axi_mm_video_WDATA,
        m_axi_mm_video_WSTRB,
        m_axi_mm_video_WLAST,
        m_axi_mm_video_WID,
        m_axi_mm_video_WUSER,
        m_axi_mm_video_ARVALID,
        m_axi_mm_video_ARREADY,
        m_axi_mm_video_ARADDR,
        m_axi_mm_video_ARID,
        m_axi_mm_video_ARLEN,
        m_axi_mm_video_ARSIZE,
        m_axi_mm_video_ARBURST,
        m_axi_mm_video_ARLOCK,
        m_axi_mm_video_ARCACHE,
        m_axi_mm_video_ARPROT,
        m_axi_mm_video_ARQOS,
        m_axi_mm_video_ARREGION,
        m_axi_mm_video_ARUSER,
        m_axi_mm_video_RVALID,
        m_axi_mm_video_RREADY,
        m_axi_mm_video_RDATA,
        m_axi_mm_video_RLAST,
        m_axi_mm_video_RID,
        m_axi_mm_video_RFIFONUM,
        m_axi_mm_video_RUSER,
        m_axi_mm_video_RRESP,
        m_axi_mm_video_BVALID,
        m_axi_mm_video_BREADY,
        m_axi_mm_video_BRESP,
        m_axi_mm_video_BID,
        m_axi_mm_video_BUSER,
        HwReg_frm_buffer,
        WidthInBytes_val2,
        colorFormat_val3,
        width_val5,
        height_val8,
        stride_val9,
        video_format_val10,
        ap_clk,
        ap_rst,
        HwReg_frm_buffer_ap_vld,
        WidthInBytes_val2_ap_vld,
        ap_start,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        height_val8_ap_vld,
        width_val5_ap_vld,
        colorFormat_val3_ap_vld,
        video_format_val10_ap_vld,
        stride_val9_ap_vld,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [47:0] s_axis_video_TDATA;
input  [5:0] s_axis_video_TKEEP;
input  [5:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
output   m_axi_mm_video_AWVALID;
input   m_axi_mm_video_AWREADY;
output  [31:0] m_axi_mm_video_AWADDR;
output  [0:0] m_axi_mm_video_AWID;
output  [31:0] m_axi_mm_video_AWLEN;
output  [2:0] m_axi_mm_video_AWSIZE;
output  [1:0] m_axi_mm_video_AWBURST;
output  [1:0] m_axi_mm_video_AWLOCK;
output  [3:0] m_axi_mm_video_AWCACHE;
output  [2:0] m_axi_mm_video_AWPROT;
output  [3:0] m_axi_mm_video_AWQOS;
output  [3:0] m_axi_mm_video_AWREGION;
output  [0:0] m_axi_mm_video_AWUSER;
output   m_axi_mm_video_WVALID;
input   m_axi_mm_video_WREADY;
output  [127:0] m_axi_mm_video_WDATA;
output  [15:0] m_axi_mm_video_WSTRB;
output   m_axi_mm_video_WLAST;
output  [0:0] m_axi_mm_video_WID;
output  [0:0] m_axi_mm_video_WUSER;
output   m_axi_mm_video_ARVALID;
input   m_axi_mm_video_ARREADY;
output  [31:0] m_axi_mm_video_ARADDR;
output  [0:0] m_axi_mm_video_ARID;
output  [31:0] m_axi_mm_video_ARLEN;
output  [2:0] m_axi_mm_video_ARSIZE;
output  [1:0] m_axi_mm_video_ARBURST;
output  [1:0] m_axi_mm_video_ARLOCK;
output  [3:0] m_axi_mm_video_ARCACHE;
output  [2:0] m_axi_mm_video_ARPROT;
output  [3:0] m_axi_mm_video_ARQOS;
output  [3:0] m_axi_mm_video_ARREGION;
output  [0:0] m_axi_mm_video_ARUSER;
input   m_axi_mm_video_RVALID;
output   m_axi_mm_video_RREADY;
input  [127:0] m_axi_mm_video_RDATA;
input   m_axi_mm_video_RLAST;
input  [0:0] m_axi_mm_video_RID;
input  [8:0] m_axi_mm_video_RFIFONUM;
input  [0:0] m_axi_mm_video_RUSER;
input  [1:0] m_axi_mm_video_RRESP;
input   m_axi_mm_video_BVALID;
output   m_axi_mm_video_BREADY;
input  [1:0] m_axi_mm_video_BRESP;
input  [0:0] m_axi_mm_video_BID;
input  [0:0] m_axi_mm_video_BUSER;
input  [31:0] HwReg_frm_buffer;
input  [14:0] WidthInBytes_val2;
input  [2:0] colorFormat_val3;
input  [11:0] width_val5;
input  [11:0] height_val8;
input  [15:0] stride_val9;
input  [5:0] video_format_val10;
input   ap_clk;
input   ap_rst;
input   HwReg_frm_buffer_ap_vld;
input   WidthInBytes_val2_ap_vld;
input   ap_start;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
input   height_val8_ap_vld;
input   width_val5_ap_vld;
input   colorFormat_val3_ap_vld;
input   video_format_val10_ap_vld;
input   stride_val9_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_start_full_n;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [31:0] entry_proc_U0_HwReg_frm_buffer_c_din;
wire    entry_proc_U0_HwReg_frm_buffer_c_write;
wire   [14:0] entry_proc_U0_WidthInBytes_val2_c11_din;
wire    entry_proc_U0_WidthInBytes_val2_c11_write;
wire    AXIvideo2MultiPixStream_U0_ap_start;
wire    AXIvideo2MultiPixStream_U0_ap_done;
wire    AXIvideo2MultiPixStream_U0_ap_continue;
wire    AXIvideo2MultiPixStream_U0_ap_idle;
wire    AXIvideo2MultiPixStream_U0_ap_ready;
wire    AXIvideo2MultiPixStream_U0_s_axis_video_TREADY;
wire   [47:0] AXIvideo2MultiPixStream_U0_img_din;
wire    AXIvideo2MultiPixStream_U0_img_write;
wire    MultiPixStream2Bytes_U0_ap_start;
wire    MultiPixStream2Bytes_U0_ap_done;
wire    MultiPixStream2Bytes_U0_ap_continue;
wire    MultiPixStream2Bytes_U0_ap_idle;
wire    MultiPixStream2Bytes_U0_ap_ready;
wire    MultiPixStream2Bytes_U0_img_read;
wire   [127:0] MultiPixStream2Bytes_U0_bytePlanes_din;
wire    MultiPixStream2Bytes_U0_bytePlanes_write;
wire   [3:0] MultiPixStream2Bytes_U0_width_val5;
wire    MultiPixStream2Bytes_U0_WidthInBytes_val2_c11_read;
wire   [14:0] MultiPixStream2Bytes_U0_WidthInBytes_val2_c_din;
wire    MultiPixStream2Bytes_U0_WidthInBytes_val2_c_write;
wire    Bytes2AXIMMvideo_U0_ap_start;
wire    Bytes2AXIMMvideo_U0_ap_done;
wire    Bytes2AXIMMvideo_U0_ap_continue;
wire    Bytes2AXIMMvideo_U0_ap_idle;
wire    Bytes2AXIMMvideo_U0_ap_ready;
wire    Bytes2AXIMMvideo_U0_bytePlanes_read;
wire    Bytes2AXIMMvideo_U0_m_axi_mm_video_AWVALID;
wire   [31:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWADDR;
wire   [0:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWID;
wire   [31:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWLEN;
wire   [2:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWSIZE;
wire   [1:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWBURST;
wire   [1:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWLOCK;
wire   [3:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWCACHE;
wire   [2:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWPROT;
wire   [3:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWQOS;
wire   [3:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWREGION;
wire   [0:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWUSER;
wire    Bytes2AXIMMvideo_U0_m_axi_mm_video_WVALID;
wire   [127:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_WDATA;
wire   [15:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_WSTRB;
wire    Bytes2AXIMMvideo_U0_m_axi_mm_video_WLAST;
wire   [0:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_WID;
wire   [0:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_WUSER;
wire    Bytes2AXIMMvideo_U0_m_axi_mm_video_ARVALID;
wire   [31:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARADDR;
wire   [0:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARID;
wire   [31:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARLEN;
wire   [2:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARSIZE;
wire   [1:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARBURST;
wire   [1:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARLOCK;
wire   [3:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARCACHE;
wire   [2:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARPROT;
wire   [3:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARQOS;
wire   [3:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARREGION;
wire   [0:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARUSER;
wire    Bytes2AXIMMvideo_U0_m_axi_mm_video_RREADY;
wire    Bytes2AXIMMvideo_U0_m_axi_mm_video_BREADY;
wire    Bytes2AXIMMvideo_U0_dstImg_read;
wire    Bytes2AXIMMvideo_U0_WidthInBytes_val_read;
wire    HwReg_frm_buffer_c_full_n;
wire   [31:0] HwReg_frm_buffer_c_dout;
wire   [2:0] HwReg_frm_buffer_c_num_data_valid;
wire   [2:0] HwReg_frm_buffer_c_fifo_cap;
wire    HwReg_frm_buffer_c_empty_n;
wire    WidthInBytes_val2_c11_full_n;
wire   [14:0] WidthInBytes_val2_c11_dout;
wire   [2:0] WidthInBytes_val2_c11_num_data_valid;
wire   [2:0] WidthInBytes_val2_c11_fifo_cap;
wire    WidthInBytes_val2_c11_empty_n;
wire    img_full_n;
wire   [47:0] img_dout;
wire   [2:0] img_num_data_valid;
wire   [2:0] img_fifo_cap;
wire    img_empty_n;
wire    bytePlanes_full_n;
wire   [127:0] bytePlanes_dout;
wire   [9:0] bytePlanes_num_data_valid;
wire   [9:0] bytePlanes_fifo_cap;
wire    bytePlanes_empty_n;
wire    WidthInBytes_val2_c_full_n;
wire   [14:0] WidthInBytes_val2_c_dout;
wire   [2:0] WidthInBytes_val2_c_num_data_valid;
wire   [2:0] WidthInBytes_val2_c_fifo_cap;
wire    WidthInBytes_val2_c_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready;
wire    ap_sync_AXIvideo2MultiPixStream_U0_ap_ready;
wire   [0:0] start_for_MultiPixStream2Bytes_U0_din;
wire    start_for_MultiPixStream2Bytes_U0_full_n;
wire   [0:0] start_for_MultiPixStream2Bytes_U0_dout;
wire    start_for_MultiPixStream2Bytes_U0_empty_n;
wire   [0:0] start_for_Bytes2AXIMMvideo_U0_din;
wire    start_for_Bytes2AXIMMvideo_U0_full_n;
wire   [0:0] start_for_Bytes2AXIMMvideo_U0_dout;
wire    start_for_Bytes2AXIMMvideo_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready = 1'b0;
end

v_frmbuf_wr_0_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(entry_proc_U0_start_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .HwReg_frm_buffer(HwReg_frm_buffer),
    .HwReg_frm_buffer_c_din(entry_proc_U0_HwReg_frm_buffer_c_din),
    .HwReg_frm_buffer_c_num_data_valid(HwReg_frm_buffer_c_num_data_valid),
    .HwReg_frm_buffer_c_fifo_cap(HwReg_frm_buffer_c_fifo_cap),
    .HwReg_frm_buffer_c_full_n(HwReg_frm_buffer_c_full_n),
    .HwReg_frm_buffer_c_write(entry_proc_U0_HwReg_frm_buffer_c_write),
    .WidthInBytes_val2(WidthInBytes_val2),
    .WidthInBytes_val2_c11_din(entry_proc_U0_WidthInBytes_val2_c11_din),
    .WidthInBytes_val2_c11_num_data_valid(WidthInBytes_val2_c11_num_data_valid),
    .WidthInBytes_val2_c11_fifo_cap(WidthInBytes_val2_c11_fifo_cap),
    .WidthInBytes_val2_c11_full_n(WidthInBytes_val2_c11_full_n),
    .WidthInBytes_val2_c11_write(entry_proc_U0_WidthInBytes_val2_c11_write)
);

v_frmbuf_wr_0_AXIvideo2MultiPixStream AXIvideo2MultiPixStream_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(AXIvideo2MultiPixStream_U0_ap_start),
    .ap_done(AXIvideo2MultiPixStream_U0_ap_done),
    .ap_continue(AXIvideo2MultiPixStream_U0_ap_continue),
    .ap_idle(AXIvideo2MultiPixStream_U0_ap_idle),
    .ap_ready(AXIvideo2MultiPixStream_U0_ap_ready),
    .s_axis_video_TDATA(s_axis_video_TDATA),
    .s_axis_video_TVALID(s_axis_video_TVALID),
    .s_axis_video_TREADY(AXIvideo2MultiPixStream_U0_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP),
    .s_axis_video_TSTRB(s_axis_video_TSTRB),
    .s_axis_video_TUSER(s_axis_video_TUSER),
    .s_axis_video_TLAST(s_axis_video_TLAST),
    .s_axis_video_TID(s_axis_video_TID),
    .s_axis_video_TDEST(s_axis_video_TDEST),
    .img_din(AXIvideo2MultiPixStream_U0_img_din),
    .img_num_data_valid(img_num_data_valid),
    .img_fifo_cap(img_fifo_cap),
    .img_full_n(img_full_n),
    .img_write(AXIvideo2MultiPixStream_U0_img_write),
    .Height_val(height_val8),
    .WidthIn_val(width_val5),
    .colorFormat_val(colorFormat_val3)
);

v_frmbuf_wr_0_MultiPixStream2Bytes MultiPixStream2Bytes_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(MultiPixStream2Bytes_U0_ap_start),
    .ap_done(MultiPixStream2Bytes_U0_ap_done),
    .ap_continue(MultiPixStream2Bytes_U0_ap_continue),
    .ap_idle(MultiPixStream2Bytes_U0_ap_idle),
    .ap_ready(MultiPixStream2Bytes_U0_ap_ready),
    .img_dout(img_dout),
    .img_num_data_valid(img_num_data_valid),
    .img_fifo_cap(img_fifo_cap),
    .img_empty_n(img_empty_n),
    .img_read(MultiPixStream2Bytes_U0_img_read),
    .bytePlanes_din(MultiPixStream2Bytes_U0_bytePlanes_din),
    .bytePlanes_num_data_valid(bytePlanes_num_data_valid),
    .bytePlanes_fifo_cap(bytePlanes_fifo_cap),
    .bytePlanes_full_n(bytePlanes_full_n),
    .bytePlanes_write(MultiPixStream2Bytes_U0_bytePlanes_write),
    .height_val8(height_val8),
    .width_val5(MultiPixStream2Bytes_U0_width_val5),
    .WidthInBytes_val2_c11_dout(WidthInBytes_val2_c11_dout),
    .WidthInBytes_val2_c11_num_data_valid(WidthInBytes_val2_c11_num_data_valid),
    .WidthInBytes_val2_c11_fifo_cap(WidthInBytes_val2_c11_fifo_cap),
    .WidthInBytes_val2_c11_empty_n(WidthInBytes_val2_c11_empty_n),
    .WidthInBytes_val2_c11_read(MultiPixStream2Bytes_U0_WidthInBytes_val2_c11_read),
    .video_format_val10(video_format_val10),
    .WidthInBytes_val2_c_din(MultiPixStream2Bytes_U0_WidthInBytes_val2_c_din),
    .WidthInBytes_val2_c_num_data_valid(WidthInBytes_val2_c_num_data_valid),
    .WidthInBytes_val2_c_fifo_cap(WidthInBytes_val2_c_fifo_cap),
    .WidthInBytes_val2_c_full_n(WidthInBytes_val2_c_full_n),
    .WidthInBytes_val2_c_write(MultiPixStream2Bytes_U0_WidthInBytes_val2_c_write)
);

v_frmbuf_wr_0_Bytes2AXIMMvideo Bytes2AXIMMvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Bytes2AXIMMvideo_U0_ap_start),
    .ap_done(Bytes2AXIMMvideo_U0_ap_done),
    .ap_continue(Bytes2AXIMMvideo_U0_ap_continue),
    .ap_idle(Bytes2AXIMMvideo_U0_ap_idle),
    .ap_ready(Bytes2AXIMMvideo_U0_ap_ready),
    .bytePlanes_dout(bytePlanes_dout),
    .bytePlanes_num_data_valid(bytePlanes_num_data_valid),
    .bytePlanes_fifo_cap(bytePlanes_fifo_cap),
    .bytePlanes_empty_n(bytePlanes_empty_n),
    .bytePlanes_read(Bytes2AXIMMvideo_U0_bytePlanes_read),
    .m_axi_mm_video_AWVALID(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWVALID),
    .m_axi_mm_video_AWREADY(m_axi_mm_video_AWREADY),
    .m_axi_mm_video_AWADDR(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWADDR),
    .m_axi_mm_video_AWID(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWID),
    .m_axi_mm_video_AWLEN(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWLEN),
    .m_axi_mm_video_AWSIZE(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWSIZE),
    .m_axi_mm_video_AWBURST(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWBURST),
    .m_axi_mm_video_AWLOCK(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWLOCK),
    .m_axi_mm_video_AWCACHE(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWCACHE),
    .m_axi_mm_video_AWPROT(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWPROT),
    .m_axi_mm_video_AWQOS(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWQOS),
    .m_axi_mm_video_AWREGION(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWREGION),
    .m_axi_mm_video_AWUSER(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWUSER),
    .m_axi_mm_video_WVALID(Bytes2AXIMMvideo_U0_m_axi_mm_video_WVALID),
    .m_axi_mm_video_WREADY(m_axi_mm_video_WREADY),
    .m_axi_mm_video_WDATA(Bytes2AXIMMvideo_U0_m_axi_mm_video_WDATA),
    .m_axi_mm_video_WSTRB(Bytes2AXIMMvideo_U0_m_axi_mm_video_WSTRB),
    .m_axi_mm_video_WLAST(Bytes2AXIMMvideo_U0_m_axi_mm_video_WLAST),
    .m_axi_mm_video_WID(Bytes2AXIMMvideo_U0_m_axi_mm_video_WID),
    .m_axi_mm_video_WUSER(Bytes2AXIMMvideo_U0_m_axi_mm_video_WUSER),
    .m_axi_mm_video_ARVALID(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARVALID),
    .m_axi_mm_video_ARREADY(1'b0),
    .m_axi_mm_video_ARADDR(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARADDR),
    .m_axi_mm_video_ARID(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARID),
    .m_axi_mm_video_ARLEN(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARLEN),
    .m_axi_mm_video_ARSIZE(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARSIZE),
    .m_axi_mm_video_ARBURST(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARBURST),
    .m_axi_mm_video_ARLOCK(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARLOCK),
    .m_axi_mm_video_ARCACHE(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARCACHE),
    .m_axi_mm_video_ARPROT(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARPROT),
    .m_axi_mm_video_ARQOS(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARQOS),
    .m_axi_mm_video_ARREGION(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARREGION),
    .m_axi_mm_video_ARUSER(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARUSER),
    .m_axi_mm_video_RVALID(1'b0),
    .m_axi_mm_video_RREADY(Bytes2AXIMMvideo_U0_m_axi_mm_video_RREADY),
    .m_axi_mm_video_RDATA(128'd0),
    .m_axi_mm_video_RLAST(1'b0),
    .m_axi_mm_video_RID(1'd0),
    .m_axi_mm_video_RFIFONUM(9'd0),
    .m_axi_mm_video_RUSER(1'd0),
    .m_axi_mm_video_RRESP(2'd0),
    .m_axi_mm_video_BVALID(m_axi_mm_video_BVALID),
    .m_axi_mm_video_BREADY(Bytes2AXIMMvideo_U0_m_axi_mm_video_BREADY),
    .m_axi_mm_video_BRESP(m_axi_mm_video_BRESP),
    .m_axi_mm_video_BID(m_axi_mm_video_BID),
    .m_axi_mm_video_BUSER(m_axi_mm_video_BUSER),
    .dstImg_dout(HwReg_frm_buffer_c_dout),
    .dstImg_num_data_valid(HwReg_frm_buffer_c_num_data_valid),
    .dstImg_fifo_cap(HwReg_frm_buffer_c_fifo_cap),
    .dstImg_empty_n(HwReg_frm_buffer_c_empty_n),
    .dstImg_read(Bytes2AXIMMvideo_U0_dstImg_read),
    .Height_val(height_val8),
    .WidthInBytes_val_dout(WidthInBytes_val2_c_dout),
    .WidthInBytes_val_num_data_valid(WidthInBytes_val2_c_num_data_valid),
    .WidthInBytes_val_fifo_cap(WidthInBytes_val2_c_fifo_cap),
    .WidthInBytes_val_empty_n(WidthInBytes_val2_c_empty_n),
    .WidthInBytes_val_read(Bytes2AXIMMvideo_U0_WidthInBytes_val_read),
    .StrideInBytes_val(stride_val9)
);

v_frmbuf_wr_0_fifo_w32_d4_S HwReg_frm_buffer_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_HwReg_frm_buffer_c_din),
    .if_full_n(HwReg_frm_buffer_c_full_n),
    .if_write(entry_proc_U0_HwReg_frm_buffer_c_write),
    .if_dout(HwReg_frm_buffer_c_dout),
    .if_num_data_valid(HwReg_frm_buffer_c_num_data_valid),
    .if_fifo_cap(HwReg_frm_buffer_c_fifo_cap),
    .if_empty_n(HwReg_frm_buffer_c_empty_n),
    .if_read(Bytes2AXIMMvideo_U0_dstImg_read)
);

v_frmbuf_wr_0_fifo_w15_d3_S WidthInBytes_val2_c11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_WidthInBytes_val2_c11_din),
    .if_full_n(WidthInBytes_val2_c11_full_n),
    .if_write(entry_proc_U0_WidthInBytes_val2_c11_write),
    .if_dout(WidthInBytes_val2_c11_dout),
    .if_num_data_valid(WidthInBytes_val2_c11_num_data_valid),
    .if_fifo_cap(WidthInBytes_val2_c11_fifo_cap),
    .if_empty_n(WidthInBytes_val2_c11_empty_n),
    .if_read(MultiPixStream2Bytes_U0_WidthInBytes_val2_c11_read)
);

v_frmbuf_wr_0_fifo_w48_d2_S img_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2MultiPixStream_U0_img_din),
    .if_full_n(img_full_n),
    .if_write(AXIvideo2MultiPixStream_U0_img_write),
    .if_dout(img_dout),
    .if_num_data_valid(img_num_data_valid),
    .if_fifo_cap(img_fifo_cap),
    .if_empty_n(img_empty_n),
    .if_read(MultiPixStream2Bytes_U0_img_read)
);

v_frmbuf_wr_0_fifo_w128_d480_B bytePlanes_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(MultiPixStream2Bytes_U0_bytePlanes_din),
    .if_full_n(bytePlanes_full_n),
    .if_write(MultiPixStream2Bytes_U0_bytePlanes_write),
    .if_dout(bytePlanes_dout),
    .if_num_data_valid(bytePlanes_num_data_valid),
    .if_fifo_cap(bytePlanes_fifo_cap),
    .if_empty_n(bytePlanes_empty_n),
    .if_read(Bytes2AXIMMvideo_U0_bytePlanes_read)
);

v_frmbuf_wr_0_fifo_w15_d2_S WidthInBytes_val2_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(MultiPixStream2Bytes_U0_WidthInBytes_val2_c_din),
    .if_full_n(WidthInBytes_val2_c_full_n),
    .if_write(MultiPixStream2Bytes_U0_WidthInBytes_val2_c_write),
    .if_dout(WidthInBytes_val2_c_dout),
    .if_num_data_valid(WidthInBytes_val2_c_num_data_valid),
    .if_fifo_cap(WidthInBytes_val2_c_fifo_cap),
    .if_empty_n(WidthInBytes_val2_c_empty_n),
    .if_read(Bytes2AXIMMvideo_U0_WidthInBytes_val_read)
);

v_frmbuf_wr_0_start_for_MultiPixStream2Bytes_U0 start_for_MultiPixStream2Bytes_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_MultiPixStream2Bytes_U0_din),
    .if_full_n(start_for_MultiPixStream2Bytes_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_MultiPixStream2Bytes_U0_dout),
    .if_empty_n(start_for_MultiPixStream2Bytes_U0_empty_n),
    .if_read(MultiPixStream2Bytes_U0_ap_ready)
);

v_frmbuf_wr_0_start_for_Bytes2AXIMMvideo_U0 start_for_Bytes2AXIMMvideo_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Bytes2AXIMMvideo_U0_din),
    .if_full_n(start_for_Bytes2AXIMMvideo_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_Bytes2AXIMMvideo_U0_dout),
    .if_empty_n(start_for_Bytes2AXIMMvideo_U0_empty_n),
    .if_read(Bytes2AXIMMvideo_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= ap_sync_AXIvideo2MultiPixStream_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

assign AXIvideo2MultiPixStream_U0_ap_continue = 1'b1;

assign AXIvideo2MultiPixStream_U0_ap_start = ((ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready ^ 1'b1) & ap_start);

assign Bytes2AXIMMvideo_U0_ap_continue = ap_continue;

assign Bytes2AXIMMvideo_U0_ap_start = start_for_Bytes2AXIMMvideo_U0_empty_n;

assign MultiPixStream2Bytes_U0_ap_continue = 1'b1;

assign MultiPixStream2Bytes_U0_ap_start = start_for_MultiPixStream2Bytes_U0_empty_n;

assign MultiPixStream2Bytes_U0_width_val5 = {{width_val5[(4 - 12'd1):0]}};

assign ap_done = Bytes2AXIMMvideo_U0_ap_done;

assign ap_idle = (entry_proc_U0_ap_idle & MultiPixStream2Bytes_U0_ap_idle & Bytes2AXIMMvideo_U0_ap_idle & AXIvideo2MultiPixStream_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_AXIvideo2MultiPixStream_U0_ap_ready = (ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready | AXIvideo2MultiPixStream_U0_ap_ready);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_entry_proc_U0_ap_ready & ap_sync_AXIvideo2MultiPixStream_U0_ap_ready);

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign entry_proc_U0_start_full_n = (start_for_MultiPixStream2Bytes_U0_full_n & start_for_Bytes2AXIMMvideo_U0_full_n);

assign m_axi_mm_video_ARADDR = 32'd0;

assign m_axi_mm_video_ARBURST = 2'd0;

assign m_axi_mm_video_ARCACHE = 4'd0;

assign m_axi_mm_video_ARID = 1'd0;

assign m_axi_mm_video_ARLEN = 32'd0;

assign m_axi_mm_video_ARLOCK = 2'd0;

assign m_axi_mm_video_ARPROT = 3'd0;

assign m_axi_mm_video_ARQOS = 4'd0;

assign m_axi_mm_video_ARREGION = 4'd0;

assign m_axi_mm_video_ARSIZE = 3'd0;

assign m_axi_mm_video_ARUSER = 1'd0;

assign m_axi_mm_video_ARVALID = 1'b0;

assign m_axi_mm_video_AWADDR = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWADDR;

assign m_axi_mm_video_AWBURST = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWBURST;

assign m_axi_mm_video_AWCACHE = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWCACHE;

assign m_axi_mm_video_AWID = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWID;

assign m_axi_mm_video_AWLEN = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWLEN;

assign m_axi_mm_video_AWLOCK = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWLOCK;

assign m_axi_mm_video_AWPROT = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWPROT;

assign m_axi_mm_video_AWQOS = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWQOS;

assign m_axi_mm_video_AWREGION = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWREGION;

assign m_axi_mm_video_AWSIZE = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWSIZE;

assign m_axi_mm_video_AWUSER = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWUSER;

assign m_axi_mm_video_AWVALID = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWVALID;

assign m_axi_mm_video_BREADY = Bytes2AXIMMvideo_U0_m_axi_mm_video_BREADY;

assign m_axi_mm_video_RREADY = 1'b0;

assign m_axi_mm_video_WDATA = Bytes2AXIMMvideo_U0_m_axi_mm_video_WDATA;

assign m_axi_mm_video_WID = Bytes2AXIMMvideo_U0_m_axi_mm_video_WID;

assign m_axi_mm_video_WLAST = Bytes2AXIMMvideo_U0_m_axi_mm_video_WLAST;

assign m_axi_mm_video_WSTRB = Bytes2AXIMMvideo_U0_m_axi_mm_video_WSTRB;

assign m_axi_mm_video_WUSER = Bytes2AXIMMvideo_U0_m_axi_mm_video_WUSER;

assign m_axi_mm_video_WVALID = Bytes2AXIMMvideo_U0_m_axi_mm_video_WVALID;

assign s_axis_video_TREADY = AXIvideo2MultiPixStream_U0_s_axis_video_TREADY;

assign start_for_Bytes2AXIMMvideo_U0_din = 1'b1;

assign start_for_MultiPixStream2Bytes_U0_din = 1'b1;

endmodule //v_frmbuf_wr_0_FrmbufWrHlsDataFlow
