-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity v_frmbuf_wr_0_MultiPixStream2Bytes is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    img_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    img_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    img_empty_n : IN STD_LOGIC;
    img_read : OUT STD_LOGIC;
    bytePlanes_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    bytePlanes_num_data_valid : IN STD_LOGIC_VECTOR (9 downto 0);
    bytePlanes_fifo_cap : IN STD_LOGIC_VECTOR (9 downto 0);
    bytePlanes_full_n : IN STD_LOGIC;
    bytePlanes_write : OUT STD_LOGIC;
    height_val8 : IN STD_LOGIC_VECTOR (11 downto 0);
    width_val5 : IN STD_LOGIC_VECTOR (3 downto 0);
    WidthInBytes_val2_c11_dout : IN STD_LOGIC_VECTOR (14 downto 0);
    WidthInBytes_val2_c11_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    WidthInBytes_val2_c11_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    WidthInBytes_val2_c11_empty_n : IN STD_LOGIC;
    WidthInBytes_val2_c11_read : OUT STD_LOGIC;
    video_format_val10 : IN STD_LOGIC_VECTOR (5 downto 0);
    WidthInBytes_val2_c_din : OUT STD_LOGIC_VECTOR (14 downto 0);
    WidthInBytes_val2_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    WidthInBytes_val2_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    WidthInBytes_val2_c_full_n : IN STD_LOGIC;
    WidthInBytes_val2_c_write : OUT STD_LOGIC );
end;


architecture behav of v_frmbuf_wr_0_MultiPixStream2Bytes is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv6_14 : STD_LOGIC_VECTOR (5 downto 0) := "010100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_15 : STD_LOGIC_VECTOR (5 downto 0) := "010101";
    constant ap_const_lv16_F : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv12_2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_const_lv25_1556 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000001010101010110";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv10_7F : STD_LOGIC_VECTOR (9 downto 0) := "0001111111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_25 : STD_LOGIC_VECTOR (5 downto 0) := "100101";
    constant ap_const_lv6_26 : STD_LOGIC_VECTOR (5 downto 0) := "100110";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_21 : STD_LOGIC_VECTOR (5 downto 0) := "100001";
    constant ap_const_lv6_16 : STD_LOGIC_VECTOR (5 downto 0) := "010110";
    constant ap_const_lv6_17 : STD_LOGIC_VECTOR (5 downto 0) := "010111";
    constant ap_const_lv6_12 : STD_LOGIC_VECTOR (5 downto 0) := "010010";
    constant ap_const_lv6_13 : STD_LOGIC_VECTOR (5 downto 0) := "010011";
    constant ap_const_lv6_1C : STD_LOGIC_VECTOR (5 downto 0) := "011100";
    constant ap_const_lv6_C : STD_LOGIC_VECTOR (5 downto 0) := "001100";
    constant ap_const_lv6_F : STD_LOGIC_VECTOR (5 downto 0) := "001111";
    constant ap_const_lv6_10 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_const_lv6_1B : STD_LOGIC_VECTOR (5 downto 0) := "011011";
    constant ap_const_lv6_A : STD_LOGIC_VECTOR (5 downto 0) := "001010";
    constant ap_const_lv6_B : STD_LOGIC_VECTOR (5 downto 0) := "001011";
    constant ap_const_lv6_29 : STD_LOGIC_VECTOR (5 downto 0) := "101001";
    constant ap_const_lv6_2A : STD_LOGIC_VECTOR (5 downto 0) := "101010";
    constant ap_const_lv6_2B : STD_LOGIC_VECTOR (5 downto 0) := "101011";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal WidthInBytes_val2_c11_blk_n : STD_LOGIC;
    signal WidthInBytes_val2_c_blk_n : STD_LOGIC;
    signal WidthInBytes_val2_c11_read_reg_531 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal video_format_val10_read_read_fu_222_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln926_fu_292_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln926_reg_596 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln1_i_reg_601 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal trunc_ln2_i_reg_607 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln930_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln930_reg_612 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal sub91_i_i_fu_399_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub91_i_i_reg_617 : STD_LOGIC_VECTOR (10 downto 0);
    signal cmp94_i_i_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp94_i_i_reg_622 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_627 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp94_2_i_i_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp94_2_i_i_reg_632 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp3_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp3_reg_637 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp94_4_i_i_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp94_4_i_i_reg_642 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp94_5_i_i_fu_454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp94_5_i_i_reg_647 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp94_6_i_i_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp94_6_i_i_reg_652 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp133_i_i_fu_466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp133_i_i_reg_657 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp6_fu_482_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp6_reg_662 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp133_2_i_i_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp133_2_i_i_reg_667 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_lcssa85_i_i_load_reg_675 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal p_lcssa7888_i_i_load_reg_680 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa7991_i_i_load_reg_685 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa8094_i_i_load_reg_690 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa8197_i_i_load_reg_695 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa82100_i_i_load_reg_700 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_start : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_done : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_idle : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_ready : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_img_read : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_bytePlanes_din : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_bytePlanes_write : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out1_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out2_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out3_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out4 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out4_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out5 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out5_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal p_lcssa82100_i_i_fu_204 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa8197_i_i_fu_200 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa8094_i_i_fu_196 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa7991_i_i_fu_192 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa7888_i_i_fu_188 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa85_i_i_fu_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_fu_180 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal y_2_fu_502_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln939_fu_497_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln925_fu_273_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln925_fu_276_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_i_fu_282_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln926_fu_306_p0 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln926_fu_306_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln926_fu_306_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal shl_ln_i_fu_322_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln934_1_i_fu_333_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln934_fu_329_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln934_1_fu_340_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln934_fu_344_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln934_fu_350_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal lshr_ln_i_fu_371_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln932_fu_380_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal remainPix_fu_384_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_410_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_432_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal remainTrx_fu_392_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_472_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal mul_ln926_fu_306_p00 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component v_frmbuf_wr_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_dout : IN STD_LOGIC_VECTOR (47 downto 0);
        img_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        img_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        img_empty_n : IN STD_LOGIC;
        img_read : OUT STD_LOGIC;
        p_lcssa82100_i_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_lcssa8197_i_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_lcssa8094_i_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_lcssa7991_i_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_lcssa7888_i_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_lcssa85_i_i : IN STD_LOGIC_VECTOR (7 downto 0);
        trunc_ln1_i : IN STD_LOGIC_VECTOR (10 downto 0);
        cmp133_2_i_i : IN STD_LOGIC_VECTOR (0 downto 0);
        icmp6 : IN STD_LOGIC_VECTOR (0 downto 0);
        bytePlanes_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        bytePlanes_num_data_valid : IN STD_LOGIC_VECTOR (9 downto 0);
        bytePlanes_fifo_cap : IN STD_LOGIC_VECTOR (9 downto 0);
        bytePlanes_full_n : IN STD_LOGIC;
        bytePlanes_write : OUT STD_LOGIC;
        cmp133_i_i : IN STD_LOGIC_VECTOR (0 downto 0);
        icmp_ln930_i : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp94_6_i_i : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp94_5_i_i : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp94_4_i_i : IN STD_LOGIC_VECTOR (0 downto 0);
        icmp3 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp94_2_i_i : IN STD_LOGIC_VECTOR (0 downto 0);
        icmp : IN STD_LOGIC_VECTOR (0 downto 0);
        sub91_i_i : IN STD_LOGIC_VECTOR (10 downto 0);
        cmp94_i_i : IN STD_LOGIC_VECTOR (0 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC;
        p_out2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out2_ap_vld : OUT STD_LOGIC;
        p_out3 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out3_ap_vld : OUT STD_LOGIC;
        p_out4 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out4_ap_vld : OUT STD_LOGIC;
        p_out5 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out5_ap_vld : OUT STD_LOGIC );
    end component;


    component v_frmbuf_wr_0_mul_12ns_14ns_25_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (11 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;



begin
    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240 : component v_frmbuf_wr_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_start,
        ap_done => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_done,
        ap_idle => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_idle,
        ap_ready => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_ready,
        img_dout => img_dout,
        img_num_data_valid => ap_const_lv3_0,
        img_fifo_cap => ap_const_lv3_0,
        img_empty_n => img_empty_n,
        img_read => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_img_read,
        p_lcssa82100_i_i => p_lcssa82100_i_i_load_reg_700,
        p_lcssa8197_i_i => p_lcssa8197_i_i_load_reg_695,
        p_lcssa8094_i_i => p_lcssa8094_i_i_load_reg_690,
        p_lcssa7991_i_i => p_lcssa7991_i_i_load_reg_685,
        p_lcssa7888_i_i => p_lcssa7888_i_i_load_reg_680,
        p_lcssa85_i_i => p_lcssa85_i_i_load_reg_675,
        trunc_ln1_i => trunc_ln1_i_reg_601,
        cmp133_2_i_i => cmp133_2_i_i_reg_667,
        icmp6 => icmp6_reg_662,
        bytePlanes_din => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_bytePlanes_din,
        bytePlanes_num_data_valid => ap_const_lv10_0,
        bytePlanes_fifo_cap => ap_const_lv10_0,
        bytePlanes_full_n => bytePlanes_full_n,
        bytePlanes_write => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_bytePlanes_write,
        cmp133_i_i => cmp133_i_i_reg_657,
        icmp_ln930_i => icmp_ln930_reg_612,
        cmp94_6_i_i => cmp94_6_i_i_reg_652,
        cmp94_5_i_i => cmp94_5_i_i_reg_647,
        cmp94_4_i_i => cmp94_4_i_i_reg_642,
        icmp3 => icmp3_reg_637,
        cmp94_2_i_i => cmp94_2_i_i_reg_632,
        icmp => icmp_reg_627,
        sub91_i_i => sub91_i_i_reg_617,
        cmp94_i_i => cmp94_i_i_reg_622,
        p_out => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out,
        p_out_ap_vld => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out_ap_vld,
        p_out1 => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out1,
        p_out1_ap_vld => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out1_ap_vld,
        p_out2 => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out2,
        p_out2_ap_vld => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out2_ap_vld,
        p_out3 => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out3,
        p_out3_ap_vld => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out3_ap_vld,
        p_out4 => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out4,
        p_out4_ap_vld => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out4_ap_vld,
        p_out5 => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out5,
        p_out5_ap_vld => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out5_ap_vld);

    mul_12ns_14ns_25_1_1_U84 : component v_frmbuf_wr_0_mul_12ns_14ns_25_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 12,
        din1_WIDTH => 14,
        dout_WIDTH => 25)
    port map (
        din0 => mul_ln926_fu_306_p0,
        din1 => mul_ln926_fu_306_p1,
        dout => mul_ln926_fu_306_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_2B) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_2A) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_29) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_B) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_A) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_1B) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_10) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_F) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_C) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_1C) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_13) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_12) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_17) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_16) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_21) or ((video_format_val10_read_read_fu_222_p2 
    = ap_const_lv6_20) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_26) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_25) or ((icmp_ln939_fu_497_p2 = ap_const_lv1_1) or (not((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_15)) and not((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_14)))))))))))))))))))))))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_ready = ap_const_logic_1)) then 
                    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_fu_180_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_15) or (video_format_val10_read_read_fu_222_p2 = ap_const_lv6_14)))) then 
                y_fu_180 <= ap_const_lv12_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_15) and (icmp_ln939_fu_497_p2 = ap_const_lv1_0)) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_14) and (icmp_ln939_fu_497_p2 = ap_const_lv1_0))))) then 
                y_fu_180 <= y_2_fu_502_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                WidthInBytes_val2_c11_read_reg_531 <= WidthInBytes_val2_c11_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln926_reg_596 <= add_ln926_fu_292_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                cmp133_2_i_i_reg_667 <= cmp133_2_i_i_fu_488_p2;
                cmp133_i_i_reg_657 <= cmp133_i_i_fu_466_p2;
                cmp94_2_i_i_reg_632 <= cmp94_2_i_i_fu_426_p2;
                cmp94_4_i_i_reg_642 <= cmp94_4_i_i_fu_448_p2;
                cmp94_5_i_i_reg_647 <= cmp94_5_i_i_fu_454_p2;
                cmp94_6_i_i_reg_652 <= cmp94_6_i_i_fu_460_p2;
                cmp94_i_i_reg_622 <= cmp94_i_i_fu_404_p2;
                icmp3_reg_637 <= icmp3_fu_442_p2;
                icmp6_reg_662 <= icmp6_fu_482_p2;
                icmp_ln930_reg_612 <= icmp_ln930_fu_366_p2;
                icmp_reg_627 <= icmp_fu_420_p2;
                sub91_i_i_reg_617 <= sub91_i_i_fu_399_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out4_ap_vld = ap_const_logic_1))) then
                p_lcssa7888_i_i_fu_188 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                p_lcssa7888_i_i_load_reg_680 <= p_lcssa7888_i_i_fu_188;
                p_lcssa7991_i_i_load_reg_685 <= p_lcssa7991_i_i_fu_192;
                p_lcssa8094_i_i_load_reg_690 <= p_lcssa8094_i_i_fu_196;
                p_lcssa8197_i_i_load_reg_695 <= p_lcssa8197_i_i_fu_200;
                p_lcssa82100_i_i_load_reg_700 <= p_lcssa82100_i_i_fu_204;
                p_lcssa85_i_i_load_reg_675 <= p_lcssa85_i_i_fu_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out3_ap_vld = ap_const_logic_1))) then
                p_lcssa7991_i_i_fu_192 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out2_ap_vld = ap_const_logic_1))) then
                p_lcssa8094_i_i_fu_196 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out1_ap_vld = ap_const_logic_1))) then
                p_lcssa8197_i_i_fu_200 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out_ap_vld = ap_const_logic_1))) then
                p_lcssa82100_i_i_fu_204 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out5_ap_vld = ap_const_logic_1))) then
                p_lcssa85_i_i_fu_184 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_p_out5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                trunc_ln1_i_reg_601 <= mul_ln926_fu_306_p2(24 downto 14);
                trunc_ln2_i_reg_607 <= add_ln934_fu_350_p2(9 downto 7);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, video_format_val10_read_read_fu_222_p2, ap_CS_fsm_state2, ap_CS_fsm_state5, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_done, ap_CS_fsm_state7, icmp_ln939_fu_497_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_2B) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_2A) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_29) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_B) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_A) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_1B) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_10) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_F) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_C) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_1C) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_13) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_12) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_17) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_16) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_21) or ((video_format_val10_read_read_fu_222_p2 
    = ap_const_lv6_20) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_26) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_25) or (not((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_15)) and not((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_14))))))))))))))))))))))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_2B) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_2A) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_29) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_B) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_A) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_1B) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_10) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_F) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_C) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_1C) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_13) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_12) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_17) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_16) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_21) or ((video_format_val10_read_read_fu_222_p2 
    = ap_const_lv6_20) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_26) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_25) or ((icmp_ln939_fu_497_p2 = ap_const_lv1_1) or (not((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_15)) and not((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_14)))))))))))))))))))))))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;

    WidthInBytes_val2_c11_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, WidthInBytes_val2_c11_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            WidthInBytes_val2_c11_blk_n <= WidthInBytes_val2_c11_empty_n;
        else 
            WidthInBytes_val2_c11_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    WidthInBytes_val2_c11_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            WidthInBytes_val2_c11_read <= ap_const_logic_1;
        else 
            WidthInBytes_val2_c11_read <= ap_const_logic_0;
        end if; 
    end process;


    WidthInBytes_val2_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, WidthInBytes_val2_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            WidthInBytes_val2_c_blk_n <= WidthInBytes_val2_c_full_n;
        else 
            WidthInBytes_val2_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    WidthInBytes_val2_c_din <= WidthInBytes_val2_c11_dout;

    WidthInBytes_val2_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            WidthInBytes_val2_c_write <= ap_const_logic_1;
        else 
            WidthInBytes_val2_c_write <= ap_const_logic_0;
        end if; 
    end process;

    add_ln925_fu_276_p2 <= std_logic_vector(unsigned(zext_ln925_fu_273_p1) + unsigned(ap_const_lv16_F));
    add_ln926_fu_292_p2 <= std_logic_vector(unsigned(trunc_ln_i_fu_282_p4) + unsigned(ap_const_lv12_2));
    add_ln934_fu_350_p2 <= std_logic_vector(unsigned(sub_ln934_fu_344_p2) + unsigned(ap_const_lv10_7F));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_done)
    begin
        if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, WidthInBytes_val2_c11_empty_n, WidthInBytes_val2_c_full_n)
    begin
                ap_block_state1 <= ((ap_const_logic_0 = WidthInBytes_val2_c_full_n) or (ap_const_logic_0 = WidthInBytes_val2_c11_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, video_format_val10_read_read_fu_222_p2, ap_CS_fsm_state5, icmp_ln939_fu_497_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_2B) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_2A) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_29) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_B) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_A) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_1B) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_10) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_F) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_C) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_1C) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_13) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_12) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_17) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_16) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_21) or ((video_format_val10_read_read_fu_222_p2 
    = ap_const_lv6_20) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_26) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_25) or ((icmp_ln939_fu_497_p2 = ap_const_lv1_1) or (not((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_15)) and not((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_14)))))))))))))))))))))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(video_format_val10_read_read_fu_222_p2, ap_CS_fsm_state5, icmp_ln939_fu_497_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_2B) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_2A) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_29) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_B) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_A) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_1B) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_10) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_F) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_C) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_1C) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_13) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_12) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_17) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_16) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_21) or ((video_format_val10_read_read_fu_222_p2 
    = ap_const_lv6_20) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_26) or ((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_25) or ((icmp_ln939_fu_497_p2 = ap_const_lv1_1) or (not((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_15)) and not((video_format_val10_read_read_fu_222_p2 = ap_const_lv6_14)))))))))))))))))))))))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bytePlanes_din <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_bytePlanes_din;

    bytePlanes_write_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_bytePlanes_write, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            bytePlanes_write <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_bytePlanes_write;
        else 
            bytePlanes_write <= ap_const_logic_0;
        end if; 
    end process;

    cmp133_2_i_i_fu_488_p2 <= "1" when (unsigned(remainTrx_fu_392_p3) > unsigned(ap_const_lv3_2)) else "0";
    cmp133_i_i_fu_466_p2 <= "0" when (remainTrx_fu_392_p3 = ap_const_lv3_0) else "1";
    cmp94_2_i_i_fu_426_p2 <= "1" when (unsigned(remainPix_fu_384_p3) > unsigned(ap_const_lv4_2)) else "0";
    cmp94_4_i_i_fu_448_p2 <= "1" when (unsigned(remainPix_fu_384_p3) > unsigned(ap_const_lv4_4)) else "0";
    cmp94_5_i_i_fu_454_p2 <= "1" when (unsigned(remainPix_fu_384_p3) > unsigned(ap_const_lv4_5)) else "0";
    cmp94_6_i_i_fu_460_p2 <= "1" when (unsigned(remainPix_fu_384_p3) > unsigned(ap_const_lv4_6)) else "0";
    cmp94_i_i_fu_404_p2 <= "0" when (remainPix_fu_384_p3 = ap_const_lv4_0) else "1";
    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_start <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_ap_start_reg;
    icmp3_fu_442_p2 <= "0" when (tmp_1_fu_432_p4 = ap_const_lv2_0) else "1";
    icmp6_fu_482_p2 <= "0" when (tmp_2_fu_472_p4 = ap_const_lv2_0) else "1";
    icmp_fu_420_p2 <= "0" when (tmp_fu_410_p4 = ap_const_lv3_0) else "1";
    icmp_ln930_fu_366_p2 <= "1" when (width_val5 = ap_const_lv4_0) else "0";
    icmp_ln939_fu_497_p2 <= "1" when (y_fu_180 = height_val8) else "0";

    img_read_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_img_read, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            img_read <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_943_1_fu_240_img_read;
        else 
            img_read <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln_i_fu_371_p4 <= width_val5(3 downto 1);
    mul_ln926_fu_306_p0 <= mul_ln926_fu_306_p00(12 - 1 downto 0);
    mul_ln926_fu_306_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln926_reg_596),25));
    mul_ln926_fu_306_p1 <= ap_const_lv25_1556(14 - 1 downto 0);
    remainPix_fu_384_p3 <= 
        ap_const_lv4_8 when (icmp_ln930_fu_366_p2(0) = '1') else 
        zext_ln932_fu_380_p1;
    remainTrx_fu_392_p3 <= 
        ap_const_lv3_3 when (icmp_ln930_fu_366_p2(0) = '1') else 
        trunc_ln2_i_reg_607;
    shl_ln934_1_i_fu_333_p3 <= (width_val5 & ap_const_lv3_0);
    shl_ln_i_fu_322_p3 <= (width_val5 & ap_const_lv5_0);
    sub91_i_i_fu_399_p2 <= std_logic_vector(unsigned(trunc_ln1_i_reg_601) + unsigned(ap_const_lv11_7FF));
    sub_ln934_fu_344_p2 <= std_logic_vector(unsigned(zext_ln934_fu_329_p1) - unsigned(zext_ln934_1_fu_340_p1));
    tmp_1_fu_432_p4 <= remainPix_fu_384_p3(3 downto 2);
    tmp_2_fu_472_p4 <= remainTrx_fu_392_p3(2 downto 1);
    tmp_fu_410_p4 <= remainPix_fu_384_p3(3 downto 1);
    trunc_ln_i_fu_282_p4 <= add_ln925_fu_276_p2(15 downto 4);
    video_format_val10_read_read_fu_222_p2 <= video_format_val10;
    y_2_fu_502_p2 <= std_logic_vector(unsigned(y_fu_180) + unsigned(ap_const_lv12_1));
    zext_ln925_fu_273_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(WidthInBytes_val2_c11_read_reg_531),16));
    zext_ln932_fu_380_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_i_fu_371_p4),4));
    zext_ln934_1_fu_340_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln934_1_i_fu_333_p3),10));
    zext_ln934_fu_329_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_i_fu_322_p3),10));
end behav;
