# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/lcd_init_bram/lcd_init_bram.xci
# IP: The module: 'lcd_init_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/lcd_init_bram/lcd_init_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lcd_init_bram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/lcd_init_bram/lcd_init_bram.xci
# IP: The module: 'lcd_init_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/lcd_init_bram/lcd_init_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lcd_init_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
