-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity v_frmbuf_wr_0_FrmbufWrHlsDataFlow is
port (
    s_axis_video_TDATA : IN STD_LOGIC_VECTOR (47 downto 0);
    s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (5 downto 0);
    s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (5 downto 0);
    s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_AWVALID : OUT STD_LOGIC;
    m_axi_mm_video_AWREADY : IN STD_LOGIC;
    m_axi_mm_video_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_mm_video_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_mm_video_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_mm_video_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mm_video_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mm_video_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mm_video_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_mm_video_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mm_video_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mm_video_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_WVALID : OUT STD_LOGIC;
    m_axi_mm_video_WREADY : IN STD_LOGIC;
    m_axi_mm_video_WDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    m_axi_mm_video_WSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_mm_video_WLAST : OUT STD_LOGIC;
    m_axi_mm_video_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_ARVALID : OUT STD_LOGIC;
    m_axi_mm_video_ARREADY : IN STD_LOGIC;
    m_axi_mm_video_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_mm_video_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_mm_video_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_mm_video_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mm_video_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mm_video_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mm_video_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_mm_video_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mm_video_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mm_video_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_RVALID : IN STD_LOGIC;
    m_axi_mm_video_RREADY : OUT STD_LOGIC;
    m_axi_mm_video_RDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    m_axi_mm_video_RLAST : IN STD_LOGIC;
    m_axi_mm_video_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_mm_video_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mm_video_BVALID : IN STD_LOGIC;
    m_axi_mm_video_BREADY : OUT STD_LOGIC;
    m_axi_mm_video_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mm_video_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    HwReg_frm_buffer : IN STD_LOGIC_VECTOR (31 downto 0);
    WidthInBytes_val2 : IN STD_LOGIC_VECTOR (14 downto 0);
    colorFormat_val3 : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val5 : IN STD_LOGIC_VECTOR (11 downto 0);
    height_val8 : IN STD_LOGIC_VECTOR (11 downto 0);
    stride_val9 : IN STD_LOGIC_VECTOR (15 downto 0);
    video_format_val10 : IN STD_LOGIC_VECTOR (5 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    HwReg_frm_buffer_ap_vld : IN STD_LOGIC;
    WidthInBytes_val2_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    s_axis_video_TVALID : IN STD_LOGIC;
    s_axis_video_TREADY : OUT STD_LOGIC;
    height_val8_ap_vld : IN STD_LOGIC;
    width_val5_ap_vld : IN STD_LOGIC;
    colorFormat_val3_ap_vld : IN STD_LOGIC;
    video_format_val10_ap_vld : IN STD_LOGIC;
    stride_val9_ap_vld : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of v_frmbuf_wr_0_FrmbufWrHlsDataFlow is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_4 : STD_LOGIC_VECTOR (11 downto 0) := "000000000100";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal entry_proc_U0_ap_start : STD_LOGIC;
    signal entry_proc_U0_start_full_n : STD_LOGIC;
    signal entry_proc_U0_ap_done : STD_LOGIC;
    signal entry_proc_U0_ap_continue : STD_LOGIC;
    signal entry_proc_U0_ap_idle : STD_LOGIC;
    signal entry_proc_U0_ap_ready : STD_LOGIC;
    signal entry_proc_U0_start_out : STD_LOGIC;
    signal entry_proc_U0_start_write : STD_LOGIC;
    signal entry_proc_U0_HwReg_frm_buffer_c_din : STD_LOGIC_VECTOR (31 downto 0);
    signal entry_proc_U0_HwReg_frm_buffer_c_write : STD_LOGIC;
    signal entry_proc_U0_WidthInBytes_val2_c11_din : STD_LOGIC_VECTOR (14 downto 0);
    signal entry_proc_U0_WidthInBytes_val2_c11_write : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_ap_start : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_ap_done : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_ap_continue : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_ap_idle : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_ap_ready : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_s_axis_video_TREADY : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_img_din : STD_LOGIC_VECTOR (47 downto 0);
    signal AXIvideo2MultiPixStream_U0_img_write : STD_LOGIC;
    signal MultiPixStream2Bytes_U0_ap_start : STD_LOGIC;
    signal MultiPixStream2Bytes_U0_ap_done : STD_LOGIC;
    signal MultiPixStream2Bytes_U0_ap_continue : STD_LOGIC;
    signal MultiPixStream2Bytes_U0_ap_idle : STD_LOGIC;
    signal MultiPixStream2Bytes_U0_ap_ready : STD_LOGIC;
    signal MultiPixStream2Bytes_U0_img_read : STD_LOGIC;
    signal MultiPixStream2Bytes_U0_bytePlanes_din : STD_LOGIC_VECTOR (127 downto 0);
    signal MultiPixStream2Bytes_U0_bytePlanes_write : STD_LOGIC;
    signal MultiPixStream2Bytes_U0_width_val5 : STD_LOGIC_VECTOR (3 downto 0);
    signal MultiPixStream2Bytes_U0_WidthInBytes_val2_c11_read : STD_LOGIC;
    signal MultiPixStream2Bytes_U0_WidthInBytes_val2_c_din : STD_LOGIC_VECTOR (14 downto 0);
    signal MultiPixStream2Bytes_U0_WidthInBytes_val2_c_write : STD_LOGIC;
    signal Bytes2AXIMMvideo_U0_ap_start : STD_LOGIC;
    signal Bytes2AXIMMvideo_U0_ap_done : STD_LOGIC;
    signal Bytes2AXIMMvideo_U0_ap_continue : STD_LOGIC;
    signal Bytes2AXIMMvideo_U0_ap_idle : STD_LOGIC;
    signal Bytes2AXIMMvideo_U0_ap_ready : STD_LOGIC;
    signal Bytes2AXIMMvideo_U0_bytePlanes_read : STD_LOGIC;
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_AWVALID : STD_LOGIC;
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_AWADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_WVALID : STD_LOGIC;
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_WDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_WSTRB : STD_LOGIC_VECTOR (15 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_WLAST : STD_LOGIC;
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_ARVALID : STD_LOGIC;
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_ARADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_RREADY : STD_LOGIC;
    signal Bytes2AXIMMvideo_U0_m_axi_mm_video_BREADY : STD_LOGIC;
    signal Bytes2AXIMMvideo_U0_dstImg_read : STD_LOGIC;
    signal Bytes2AXIMMvideo_U0_WidthInBytes_val_read : STD_LOGIC;
    signal HwReg_frm_buffer_c_full_n : STD_LOGIC;
    signal HwReg_frm_buffer_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal HwReg_frm_buffer_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal HwReg_frm_buffer_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal HwReg_frm_buffer_c_empty_n : STD_LOGIC;
    signal WidthInBytes_val2_c11_full_n : STD_LOGIC;
    signal WidthInBytes_val2_c11_dout : STD_LOGIC_VECTOR (14 downto 0);
    signal WidthInBytes_val2_c11_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal WidthInBytes_val2_c11_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal WidthInBytes_val2_c11_empty_n : STD_LOGIC;
    signal img_full_n : STD_LOGIC;
    signal img_dout : STD_LOGIC_VECTOR (47 downto 0);
    signal img_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal img_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal img_empty_n : STD_LOGIC;
    signal bytePlanes_full_n : STD_LOGIC;
    signal bytePlanes_dout : STD_LOGIC_VECTOR (127 downto 0);
    signal bytePlanes_num_data_valid : STD_LOGIC_VECTOR (9 downto 0);
    signal bytePlanes_fifo_cap : STD_LOGIC_VECTOR (9 downto 0);
    signal bytePlanes_empty_n : STD_LOGIC;
    signal WidthInBytes_val2_c_full_n : STD_LOGIC;
    signal WidthInBytes_val2_c_dout : STD_LOGIC_VECTOR (14 downto 0);
    signal WidthInBytes_val2_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal WidthInBytes_val2_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal WidthInBytes_val2_c_empty_n : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_entry_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_entry_proc_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_AXIvideo2MultiPixStream_U0_ap_ready : STD_LOGIC;
    signal start_for_MultiPixStream2Bytes_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_MultiPixStream2Bytes_U0_full_n : STD_LOGIC;
    signal start_for_MultiPixStream2Bytes_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_MultiPixStream2Bytes_U0_empty_n : STD_LOGIC;
    signal start_for_Bytes2AXIMMvideo_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Bytes2AXIMMvideo_U0_full_n : STD_LOGIC;
    signal start_for_Bytes2AXIMMvideo_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Bytes2AXIMMvideo_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component v_frmbuf_wr_0_entry_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        HwReg_frm_buffer : IN STD_LOGIC_VECTOR (31 downto 0);
        HwReg_frm_buffer_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        HwReg_frm_buffer_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        HwReg_frm_buffer_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        HwReg_frm_buffer_c_full_n : IN STD_LOGIC;
        HwReg_frm_buffer_c_write : OUT STD_LOGIC;
        WidthInBytes_val2 : IN STD_LOGIC_VECTOR (14 downto 0);
        WidthInBytes_val2_c11_din : OUT STD_LOGIC_VECTOR (14 downto 0);
        WidthInBytes_val2_c11_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        WidthInBytes_val2_c11_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        WidthInBytes_val2_c11_full_n : IN STD_LOGIC;
        WidthInBytes_val2_c11_write : OUT STD_LOGIC );
    end component;


    component v_frmbuf_wr_0_AXIvideo2MultiPixStream IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video_TDATA : IN STD_LOGIC_VECTOR (47 downto 0);
        s_axis_video_TVALID : IN STD_LOGIC;
        s_axis_video_TREADY : OUT STD_LOGIC;
        s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (5 downto 0);
        s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (5 downto 0);
        s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        img_din : OUT STD_LOGIC_VECTOR (47 downto 0);
        img_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        img_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        img_full_n : IN STD_LOGIC;
        img_write : OUT STD_LOGIC;
        Height_val : IN STD_LOGIC_VECTOR (11 downto 0);
        WidthIn_val : IN STD_LOGIC_VECTOR (11 downto 0);
        colorFormat_val : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component v_frmbuf_wr_0_MultiPixStream2Bytes IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_dout : IN STD_LOGIC_VECTOR (47 downto 0);
        img_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        img_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        img_empty_n : IN STD_LOGIC;
        img_read : OUT STD_LOGIC;
        bytePlanes_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        bytePlanes_num_data_valid : IN STD_LOGIC_VECTOR (9 downto 0);
        bytePlanes_fifo_cap : IN STD_LOGIC_VECTOR (9 downto 0);
        bytePlanes_full_n : IN STD_LOGIC;
        bytePlanes_write : OUT STD_LOGIC;
        height_val8 : IN STD_LOGIC_VECTOR (11 downto 0);
        width_val5 : IN STD_LOGIC_VECTOR (3 downto 0);
        WidthInBytes_val2_c11_dout : IN STD_LOGIC_VECTOR (14 downto 0);
        WidthInBytes_val2_c11_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        WidthInBytes_val2_c11_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        WidthInBytes_val2_c11_empty_n : IN STD_LOGIC;
        WidthInBytes_val2_c11_read : OUT STD_LOGIC;
        video_format_val10 : IN STD_LOGIC_VECTOR (5 downto 0);
        WidthInBytes_val2_c_din : OUT STD_LOGIC_VECTOR (14 downto 0);
        WidthInBytes_val2_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        WidthInBytes_val2_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        WidthInBytes_val2_c_full_n : IN STD_LOGIC;
        WidthInBytes_val2_c_write : OUT STD_LOGIC );
    end component;


    component v_frmbuf_wr_0_Bytes2AXIMMvideo IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bytePlanes_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        bytePlanes_num_data_valid : IN STD_LOGIC_VECTOR (9 downto 0);
        bytePlanes_fifo_cap : IN STD_LOGIC_VECTOR (9 downto 0);
        bytePlanes_empty_n : IN STD_LOGIC;
        bytePlanes_read : OUT STD_LOGIC;
        m_axi_mm_video_AWVALID : OUT STD_LOGIC;
        m_axi_mm_video_AWREADY : IN STD_LOGIC;
        m_axi_mm_video_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_mm_video_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mm_video_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_mm_video_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_mm_video_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_mm_video_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_mm_video_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_mm_video_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_mm_video_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_mm_video_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_mm_video_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mm_video_WVALID : OUT STD_LOGIC;
        m_axi_mm_video_WREADY : IN STD_LOGIC;
        m_axi_mm_video_WDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        m_axi_mm_video_WSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
        m_axi_mm_video_WLAST : OUT STD_LOGIC;
        m_axi_mm_video_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mm_video_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mm_video_ARVALID : OUT STD_LOGIC;
        m_axi_mm_video_ARREADY : IN STD_LOGIC;
        m_axi_mm_video_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_mm_video_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mm_video_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_mm_video_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_mm_video_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_mm_video_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_mm_video_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_mm_video_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_mm_video_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_mm_video_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_mm_video_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mm_video_RVALID : IN STD_LOGIC;
        m_axi_mm_video_RREADY : OUT STD_LOGIC;
        m_axi_mm_video_RDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        m_axi_mm_video_RLAST : IN STD_LOGIC;
        m_axi_mm_video_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mm_video_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_mm_video_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mm_video_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_mm_video_BVALID : IN STD_LOGIC;
        m_axi_mm_video_BREADY : OUT STD_LOGIC;
        m_axi_mm_video_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_mm_video_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mm_video_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        dstImg_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        dstImg_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        dstImg_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        dstImg_empty_n : IN STD_LOGIC;
        dstImg_read : OUT STD_LOGIC;
        Height_val : IN STD_LOGIC_VECTOR (11 downto 0);
        WidthInBytes_val_dout : IN STD_LOGIC_VECTOR (14 downto 0);
        WidthInBytes_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        WidthInBytes_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        WidthInBytes_val_empty_n : IN STD_LOGIC;
        WidthInBytes_val_read : OUT STD_LOGIC;
        StrideInBytes_val : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component v_frmbuf_wr_0_fifo_w32_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component v_frmbuf_wr_0_fifo_w15_d3_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (14 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (14 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component v_frmbuf_wr_0_fifo_w48_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (47 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (47 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component v_frmbuf_wr_0_fifo_w128_d480_B IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (127 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (127 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (9 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (9 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component v_frmbuf_wr_0_fifo_w15_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (14 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (14 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component v_frmbuf_wr_0_start_for_MultiPixStream2Bytes_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component v_frmbuf_wr_0_start_for_Bytes2AXIMMvideo_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    entry_proc_U0 : component v_frmbuf_wr_0_entry_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => entry_proc_U0_ap_start,
        start_full_n => entry_proc_U0_start_full_n,
        ap_done => entry_proc_U0_ap_done,
        ap_continue => entry_proc_U0_ap_continue,
        ap_idle => entry_proc_U0_ap_idle,
        ap_ready => entry_proc_U0_ap_ready,
        start_out => entry_proc_U0_start_out,
        start_write => entry_proc_U0_start_write,
        HwReg_frm_buffer => HwReg_frm_buffer,
        HwReg_frm_buffer_c_din => entry_proc_U0_HwReg_frm_buffer_c_din,
        HwReg_frm_buffer_c_num_data_valid => HwReg_frm_buffer_c_num_data_valid,
        HwReg_frm_buffer_c_fifo_cap => HwReg_frm_buffer_c_fifo_cap,
        HwReg_frm_buffer_c_full_n => HwReg_frm_buffer_c_full_n,
        HwReg_frm_buffer_c_write => entry_proc_U0_HwReg_frm_buffer_c_write,
        WidthInBytes_val2 => WidthInBytes_val2,
        WidthInBytes_val2_c11_din => entry_proc_U0_WidthInBytes_val2_c11_din,
        WidthInBytes_val2_c11_num_data_valid => WidthInBytes_val2_c11_num_data_valid,
        WidthInBytes_val2_c11_fifo_cap => WidthInBytes_val2_c11_fifo_cap,
        WidthInBytes_val2_c11_full_n => WidthInBytes_val2_c11_full_n,
        WidthInBytes_val2_c11_write => entry_proc_U0_WidthInBytes_val2_c11_write);

    AXIvideo2MultiPixStream_U0 : component v_frmbuf_wr_0_AXIvideo2MultiPixStream
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => AXIvideo2MultiPixStream_U0_ap_start,
        ap_done => AXIvideo2MultiPixStream_U0_ap_done,
        ap_continue => AXIvideo2MultiPixStream_U0_ap_continue,
        ap_idle => AXIvideo2MultiPixStream_U0_ap_idle,
        ap_ready => AXIvideo2MultiPixStream_U0_ap_ready,
        s_axis_video_TDATA => s_axis_video_TDATA,
        s_axis_video_TVALID => s_axis_video_TVALID,
        s_axis_video_TREADY => AXIvideo2MultiPixStream_U0_s_axis_video_TREADY,
        s_axis_video_TKEEP => s_axis_video_TKEEP,
        s_axis_video_TSTRB => s_axis_video_TSTRB,
        s_axis_video_TUSER => s_axis_video_TUSER,
        s_axis_video_TLAST => s_axis_video_TLAST,
        s_axis_video_TID => s_axis_video_TID,
        s_axis_video_TDEST => s_axis_video_TDEST,
        img_din => AXIvideo2MultiPixStream_U0_img_din,
        img_num_data_valid => img_num_data_valid,
        img_fifo_cap => img_fifo_cap,
        img_full_n => img_full_n,
        img_write => AXIvideo2MultiPixStream_U0_img_write,
        Height_val => height_val8,
        WidthIn_val => width_val5,
        colorFormat_val => colorFormat_val3);

    MultiPixStream2Bytes_U0 : component v_frmbuf_wr_0_MultiPixStream2Bytes
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => MultiPixStream2Bytes_U0_ap_start,
        ap_done => MultiPixStream2Bytes_U0_ap_done,
        ap_continue => MultiPixStream2Bytes_U0_ap_continue,
        ap_idle => MultiPixStream2Bytes_U0_ap_idle,
        ap_ready => MultiPixStream2Bytes_U0_ap_ready,
        img_dout => img_dout,
        img_num_data_valid => img_num_data_valid,
        img_fifo_cap => img_fifo_cap,
        img_empty_n => img_empty_n,
        img_read => MultiPixStream2Bytes_U0_img_read,
        bytePlanes_din => MultiPixStream2Bytes_U0_bytePlanes_din,
        bytePlanes_num_data_valid => bytePlanes_num_data_valid,
        bytePlanes_fifo_cap => bytePlanes_fifo_cap,
        bytePlanes_full_n => bytePlanes_full_n,
        bytePlanes_write => MultiPixStream2Bytes_U0_bytePlanes_write,
        height_val8 => height_val8,
        width_val5 => MultiPixStream2Bytes_U0_width_val5,
        WidthInBytes_val2_c11_dout => WidthInBytes_val2_c11_dout,
        WidthInBytes_val2_c11_num_data_valid => WidthInBytes_val2_c11_num_data_valid,
        WidthInBytes_val2_c11_fifo_cap => WidthInBytes_val2_c11_fifo_cap,
        WidthInBytes_val2_c11_empty_n => WidthInBytes_val2_c11_empty_n,
        WidthInBytes_val2_c11_read => MultiPixStream2Bytes_U0_WidthInBytes_val2_c11_read,
        video_format_val10 => video_format_val10,
        WidthInBytes_val2_c_din => MultiPixStream2Bytes_U0_WidthInBytes_val2_c_din,
        WidthInBytes_val2_c_num_data_valid => WidthInBytes_val2_c_num_data_valid,
        WidthInBytes_val2_c_fifo_cap => WidthInBytes_val2_c_fifo_cap,
        WidthInBytes_val2_c_full_n => WidthInBytes_val2_c_full_n,
        WidthInBytes_val2_c_write => MultiPixStream2Bytes_U0_WidthInBytes_val2_c_write);

    Bytes2AXIMMvideo_U0 : component v_frmbuf_wr_0_Bytes2AXIMMvideo
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => Bytes2AXIMMvideo_U0_ap_start,
        ap_done => Bytes2AXIMMvideo_U0_ap_done,
        ap_continue => Bytes2AXIMMvideo_U0_ap_continue,
        ap_idle => Bytes2AXIMMvideo_U0_ap_idle,
        ap_ready => Bytes2AXIMMvideo_U0_ap_ready,
        bytePlanes_dout => bytePlanes_dout,
        bytePlanes_num_data_valid => bytePlanes_num_data_valid,
        bytePlanes_fifo_cap => bytePlanes_fifo_cap,
        bytePlanes_empty_n => bytePlanes_empty_n,
        bytePlanes_read => Bytes2AXIMMvideo_U0_bytePlanes_read,
        m_axi_mm_video_AWVALID => Bytes2AXIMMvideo_U0_m_axi_mm_video_AWVALID,
        m_axi_mm_video_AWREADY => m_axi_mm_video_AWREADY,
        m_axi_mm_video_AWADDR => Bytes2AXIMMvideo_U0_m_axi_mm_video_AWADDR,
        m_axi_mm_video_AWID => Bytes2AXIMMvideo_U0_m_axi_mm_video_AWID,
        m_axi_mm_video_AWLEN => Bytes2AXIMMvideo_U0_m_axi_mm_video_AWLEN,
        m_axi_mm_video_AWSIZE => Bytes2AXIMMvideo_U0_m_axi_mm_video_AWSIZE,
        m_axi_mm_video_AWBURST => Bytes2AXIMMvideo_U0_m_axi_mm_video_AWBURST,
        m_axi_mm_video_AWLOCK => Bytes2AXIMMvideo_U0_m_axi_mm_video_AWLOCK,
        m_axi_mm_video_AWCACHE => Bytes2AXIMMvideo_U0_m_axi_mm_video_AWCACHE,
        m_axi_mm_video_AWPROT => Bytes2AXIMMvideo_U0_m_axi_mm_video_AWPROT,
        m_axi_mm_video_AWQOS => Bytes2AXIMMvideo_U0_m_axi_mm_video_AWQOS,
        m_axi_mm_video_AWREGION => Bytes2AXIMMvideo_U0_m_axi_mm_video_AWREGION,
        m_axi_mm_video_AWUSER => Bytes2AXIMMvideo_U0_m_axi_mm_video_AWUSER,
        m_axi_mm_video_WVALID => Bytes2AXIMMvideo_U0_m_axi_mm_video_WVALID,
        m_axi_mm_video_WREADY => m_axi_mm_video_WREADY,
        m_axi_mm_video_WDATA => Bytes2AXIMMvideo_U0_m_axi_mm_video_WDATA,
        m_axi_mm_video_WSTRB => Bytes2AXIMMvideo_U0_m_axi_mm_video_WSTRB,
        m_axi_mm_video_WLAST => Bytes2AXIMMvideo_U0_m_axi_mm_video_WLAST,
        m_axi_mm_video_WID => Bytes2AXIMMvideo_U0_m_axi_mm_video_WID,
        m_axi_mm_video_WUSER => Bytes2AXIMMvideo_U0_m_axi_mm_video_WUSER,
        m_axi_mm_video_ARVALID => Bytes2AXIMMvideo_U0_m_axi_mm_video_ARVALID,
        m_axi_mm_video_ARREADY => ap_const_logic_0,
        m_axi_mm_video_ARADDR => Bytes2AXIMMvideo_U0_m_axi_mm_video_ARADDR,
        m_axi_mm_video_ARID => Bytes2AXIMMvideo_U0_m_axi_mm_video_ARID,
        m_axi_mm_video_ARLEN => Bytes2AXIMMvideo_U0_m_axi_mm_video_ARLEN,
        m_axi_mm_video_ARSIZE => Bytes2AXIMMvideo_U0_m_axi_mm_video_ARSIZE,
        m_axi_mm_video_ARBURST => Bytes2AXIMMvideo_U0_m_axi_mm_video_ARBURST,
        m_axi_mm_video_ARLOCK => Bytes2AXIMMvideo_U0_m_axi_mm_video_ARLOCK,
        m_axi_mm_video_ARCACHE => Bytes2AXIMMvideo_U0_m_axi_mm_video_ARCACHE,
        m_axi_mm_video_ARPROT => Bytes2AXIMMvideo_U0_m_axi_mm_video_ARPROT,
        m_axi_mm_video_ARQOS => Bytes2AXIMMvideo_U0_m_axi_mm_video_ARQOS,
        m_axi_mm_video_ARREGION => Bytes2AXIMMvideo_U0_m_axi_mm_video_ARREGION,
        m_axi_mm_video_ARUSER => Bytes2AXIMMvideo_U0_m_axi_mm_video_ARUSER,
        m_axi_mm_video_RVALID => ap_const_logic_0,
        m_axi_mm_video_RREADY => Bytes2AXIMMvideo_U0_m_axi_mm_video_RREADY,
        m_axi_mm_video_RDATA => ap_const_lv128_lc_1,
        m_axi_mm_video_RLAST => ap_const_logic_0,
        m_axi_mm_video_RID => ap_const_lv1_0,
        m_axi_mm_video_RFIFONUM => ap_const_lv9_0,
        m_axi_mm_video_RUSER => ap_const_lv1_0,
        m_axi_mm_video_RRESP => ap_const_lv2_0,
        m_axi_mm_video_BVALID => m_axi_mm_video_BVALID,
        m_axi_mm_video_BREADY => Bytes2AXIMMvideo_U0_m_axi_mm_video_BREADY,
        m_axi_mm_video_BRESP => m_axi_mm_video_BRESP,
        m_axi_mm_video_BID => m_axi_mm_video_BID,
        m_axi_mm_video_BUSER => m_axi_mm_video_BUSER,
        dstImg_dout => HwReg_frm_buffer_c_dout,
        dstImg_num_data_valid => HwReg_frm_buffer_c_num_data_valid,
        dstImg_fifo_cap => HwReg_frm_buffer_c_fifo_cap,
        dstImg_empty_n => HwReg_frm_buffer_c_empty_n,
        dstImg_read => Bytes2AXIMMvideo_U0_dstImg_read,
        Height_val => height_val8,
        WidthInBytes_val_dout => WidthInBytes_val2_c_dout,
        WidthInBytes_val_num_data_valid => WidthInBytes_val2_c_num_data_valid,
        WidthInBytes_val_fifo_cap => WidthInBytes_val2_c_fifo_cap,
        WidthInBytes_val_empty_n => WidthInBytes_val2_c_empty_n,
        WidthInBytes_val_read => Bytes2AXIMMvideo_U0_WidthInBytes_val_read,
        StrideInBytes_val => stride_val9);

    HwReg_frm_buffer_c_U : component v_frmbuf_wr_0_fifo_w32_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_HwReg_frm_buffer_c_din,
        if_full_n => HwReg_frm_buffer_c_full_n,
        if_write => entry_proc_U0_HwReg_frm_buffer_c_write,
        if_dout => HwReg_frm_buffer_c_dout,
        if_num_data_valid => HwReg_frm_buffer_c_num_data_valid,
        if_fifo_cap => HwReg_frm_buffer_c_fifo_cap,
        if_empty_n => HwReg_frm_buffer_c_empty_n,
        if_read => Bytes2AXIMMvideo_U0_dstImg_read);

    WidthInBytes_val2_c11_U : component v_frmbuf_wr_0_fifo_w15_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_WidthInBytes_val2_c11_din,
        if_full_n => WidthInBytes_val2_c11_full_n,
        if_write => entry_proc_U0_WidthInBytes_val2_c11_write,
        if_dout => WidthInBytes_val2_c11_dout,
        if_num_data_valid => WidthInBytes_val2_c11_num_data_valid,
        if_fifo_cap => WidthInBytes_val2_c11_fifo_cap,
        if_empty_n => WidthInBytes_val2_c11_empty_n,
        if_read => MultiPixStream2Bytes_U0_WidthInBytes_val2_c11_read);

    img_U : component v_frmbuf_wr_0_fifo_w48_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2MultiPixStream_U0_img_din,
        if_full_n => img_full_n,
        if_write => AXIvideo2MultiPixStream_U0_img_write,
        if_dout => img_dout,
        if_num_data_valid => img_num_data_valid,
        if_fifo_cap => img_fifo_cap,
        if_empty_n => img_empty_n,
        if_read => MultiPixStream2Bytes_U0_img_read);

    bytePlanes_U : component v_frmbuf_wr_0_fifo_w128_d480_B
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => MultiPixStream2Bytes_U0_bytePlanes_din,
        if_full_n => bytePlanes_full_n,
        if_write => MultiPixStream2Bytes_U0_bytePlanes_write,
        if_dout => bytePlanes_dout,
        if_num_data_valid => bytePlanes_num_data_valid,
        if_fifo_cap => bytePlanes_fifo_cap,
        if_empty_n => bytePlanes_empty_n,
        if_read => Bytes2AXIMMvideo_U0_bytePlanes_read);

    WidthInBytes_val2_c_U : component v_frmbuf_wr_0_fifo_w15_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => MultiPixStream2Bytes_U0_WidthInBytes_val2_c_din,
        if_full_n => WidthInBytes_val2_c_full_n,
        if_write => MultiPixStream2Bytes_U0_WidthInBytes_val2_c_write,
        if_dout => WidthInBytes_val2_c_dout,
        if_num_data_valid => WidthInBytes_val2_c_num_data_valid,
        if_fifo_cap => WidthInBytes_val2_c_fifo_cap,
        if_empty_n => WidthInBytes_val2_c_empty_n,
        if_read => Bytes2AXIMMvideo_U0_WidthInBytes_val_read);

    start_for_MultiPixStream2Bytes_U0_U : component v_frmbuf_wr_0_start_for_MultiPixStream2Bytes_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_MultiPixStream2Bytes_U0_din,
        if_full_n => start_for_MultiPixStream2Bytes_U0_full_n,
        if_write => entry_proc_U0_start_write,
        if_dout => start_for_MultiPixStream2Bytes_U0_dout,
        if_empty_n => start_for_MultiPixStream2Bytes_U0_empty_n,
        if_read => MultiPixStream2Bytes_U0_ap_ready);

    start_for_Bytes2AXIMMvideo_U0_U : component v_frmbuf_wr_0_start_for_Bytes2AXIMMvideo_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Bytes2AXIMMvideo_U0_din,
        if_full_n => start_for_Bytes2AXIMMvideo_U0_full_n,
        if_write => entry_proc_U0_start_write,
        if_dout => start_for_Bytes2AXIMMvideo_U0_dout,
        if_empty_n => start_for_Bytes2AXIMMvideo_U0_empty_n,
        if_read => Bytes2AXIMMvideo_U0_ap_ready);





    ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= ap_sync_AXIvideo2MultiPixStream_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_entry_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    AXIvideo2MultiPixStream_U0_ap_continue <= ap_const_logic_1;
    AXIvideo2MultiPixStream_U0_ap_start <= ((ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready xor ap_const_logic_1) and ap_start);
    Bytes2AXIMMvideo_U0_ap_continue <= ap_continue;
    Bytes2AXIMMvideo_U0_ap_start <= start_for_Bytes2AXIMMvideo_U0_empty_n;
    MultiPixStream2Bytes_U0_ap_continue <= ap_const_logic_1;
    MultiPixStream2Bytes_U0_ap_start <= start_for_MultiPixStream2Bytes_U0_empty_n;
    
    MultiPixStream2Bytes_U0_width_val5_proc : process(width_val5)
    variable vlo_cpy : STD_LOGIC_VECTOR(12+12 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(12+12 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(12 - 1 downto 0);
    variable MultiPixStream2Bytes_U0_width_val5_i : integer;
    variable section : STD_LOGIC_VECTOR(12 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(12 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(12 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(4 - 1 downto 0) := ap_const_lv12_0(4 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(4 - 1 downto 0) := ap_const_lv12_4(4 - 1 downto 0);
        v0_cpy := width_val5;
        if (vlo_cpy(4 - 1 downto 0) > vhi_cpy(4 - 1 downto 0)) then
            vhi_cpy(4-1 downto 0) := std_logic_vector(12-1-unsigned(ap_const_lv12_4(4-1 downto 0)));
            vlo_cpy(4-1 downto 0) := std_logic_vector(12-1-unsigned(ap_const_lv12_0(4-1 downto 0)));
            for MultiPixStream2Bytes_U0_width_val5_i in 0 to 12-1 loop
                v0_cpy(MultiPixStream2Bytes_U0_width_val5_i) := width_val5(12-1-MultiPixStream2Bytes_U0_width_val5_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(4-1 downto 0)))));

        section := (others=>'0');
        section(4-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(4-1 downto 0)) - unsigned(vlo_cpy(4-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(12-1 downto 0)))));
        res_mask := res_mask(12-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        MultiPixStream2Bytes_U0_width_val5 <= resvalue(4-1 downto 0);
    end process;

    ap_done <= Bytes2AXIMMvideo_U0_ap_done;
    ap_idle <= (entry_proc_U0_ap_idle and MultiPixStream2Bytes_U0_ap_idle and Bytes2AXIMMvideo_U0_ap_idle and AXIvideo2MultiPixStream_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_AXIvideo2MultiPixStream_U0_ap_ready <= (ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready or AXIvideo2MultiPixStream_U0_ap_ready);
    ap_sync_entry_proc_U0_ap_ready <= (entry_proc_U0_ap_ready or ap_sync_reg_entry_proc_U0_ap_ready);
    ap_sync_ready <= (ap_sync_entry_proc_U0_ap_ready and ap_sync_AXIvideo2MultiPixStream_U0_ap_ready);
    entry_proc_U0_ap_continue <= ap_const_logic_1;
    entry_proc_U0_ap_start <= ((ap_sync_reg_entry_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    entry_proc_U0_start_full_n <= (start_for_MultiPixStream2Bytes_U0_full_n and start_for_Bytes2AXIMMvideo_U0_full_n);
    m_axi_mm_video_ARADDR <= ap_const_lv32_0;
    m_axi_mm_video_ARBURST <= ap_const_lv2_0;
    m_axi_mm_video_ARCACHE <= ap_const_lv4_0;
    m_axi_mm_video_ARID <= ap_const_lv1_0;
    m_axi_mm_video_ARLEN <= ap_const_lv32_0;
    m_axi_mm_video_ARLOCK <= ap_const_lv2_0;
    m_axi_mm_video_ARPROT <= ap_const_lv3_0;
    m_axi_mm_video_ARQOS <= ap_const_lv4_0;
    m_axi_mm_video_ARREGION <= ap_const_lv4_0;
    m_axi_mm_video_ARSIZE <= ap_const_lv3_0;
    m_axi_mm_video_ARUSER <= ap_const_lv1_0;
    m_axi_mm_video_ARVALID <= ap_const_logic_0;
    m_axi_mm_video_AWADDR <= Bytes2AXIMMvideo_U0_m_axi_mm_video_AWADDR;
    m_axi_mm_video_AWBURST <= Bytes2AXIMMvideo_U0_m_axi_mm_video_AWBURST;
    m_axi_mm_video_AWCACHE <= Bytes2AXIMMvideo_U0_m_axi_mm_video_AWCACHE;
    m_axi_mm_video_AWID <= Bytes2AXIMMvideo_U0_m_axi_mm_video_AWID;
    m_axi_mm_video_AWLEN <= Bytes2AXIMMvideo_U0_m_axi_mm_video_AWLEN;
    m_axi_mm_video_AWLOCK <= Bytes2AXIMMvideo_U0_m_axi_mm_video_AWLOCK;
    m_axi_mm_video_AWPROT <= Bytes2AXIMMvideo_U0_m_axi_mm_video_AWPROT;
    m_axi_mm_video_AWQOS <= Bytes2AXIMMvideo_U0_m_axi_mm_video_AWQOS;
    m_axi_mm_video_AWREGION <= Bytes2AXIMMvideo_U0_m_axi_mm_video_AWREGION;
    m_axi_mm_video_AWSIZE <= Bytes2AXIMMvideo_U0_m_axi_mm_video_AWSIZE;
    m_axi_mm_video_AWUSER <= Bytes2AXIMMvideo_U0_m_axi_mm_video_AWUSER;
    m_axi_mm_video_AWVALID <= Bytes2AXIMMvideo_U0_m_axi_mm_video_AWVALID;
    m_axi_mm_video_BREADY <= Bytes2AXIMMvideo_U0_m_axi_mm_video_BREADY;
    m_axi_mm_video_RREADY <= ap_const_logic_0;
    m_axi_mm_video_WDATA <= Bytes2AXIMMvideo_U0_m_axi_mm_video_WDATA;
    m_axi_mm_video_WID <= Bytes2AXIMMvideo_U0_m_axi_mm_video_WID;
    m_axi_mm_video_WLAST <= Bytes2AXIMMvideo_U0_m_axi_mm_video_WLAST;
    m_axi_mm_video_WSTRB <= Bytes2AXIMMvideo_U0_m_axi_mm_video_WSTRB;
    m_axi_mm_video_WUSER <= Bytes2AXIMMvideo_U0_m_axi_mm_video_WUSER;
    m_axi_mm_video_WVALID <= Bytes2AXIMMvideo_U0_m_axi_mm_video_WVALID;
    s_axis_video_TREADY <= AXIvideo2MultiPixStream_U0_s_axis_video_TREADY;
    start_for_Bytes2AXIMMvideo_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_MultiPixStream2Bytes_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
