<AutoPilot:project xmlns:AutoPilot="com.autoesl.autopilot.project" projectType="C/C++" top="v_frmbuf_wr" name="prj">
    <solutions>
        <solution name="sol" status=""/>
    </solutions>
    <files>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls/hls_video_undistort.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls/hls_video_types.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls/hls_video_stereobm.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls/hls_video_mem.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls/hls_video_io.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls/hls_video_imgproc.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls/hls_video_imgbase.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls/hls_video_hough.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls/hls_video_histogram.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls/hls_video_harris.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls/hls_video_haar.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls/hls_video_fast.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls/hls_video_core.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls/hls_video_arithm.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls/hls_axi_io.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls_opencv.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls_video.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/v_frmbuf_wr.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/v_frmbuf_wr.cpp" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
        <file name="C:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/v_frmbuf_wr_config.h" sc="0" tb="false" cflags="-IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src/hls -IC:/Users/XF/Desktop/chiplabdemo/chiplab/fpga/loongson/2023.2/system_run.runs/v_frmbuf_wr_0_synth_1/c_files/src" csimflags="" blackbox="false"/>
    </files>
</AutoPilot:project>

