# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/v_frmbuf_wr_0/v_frmbuf_wr_0.xci
# IP: The module: 'v_frmbuf_wr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/v_frmbuf_wr_0/v_frmbuf_wr_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_frmbuf_wr_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/v_frmbuf_wr_0/v_frmbuf_wr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_frmbuf_wr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/v_frmbuf_wr_0/v_frmbuf_wr_0.xci
# IP: The module: 'v_frmbuf_wr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/v_frmbuf_wr_0/v_frmbuf_wr_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_frmbuf_wr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/v_frmbuf_wr_0/v_frmbuf_wr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_frmbuf_wr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
