# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/gt9147_init/gt9147_init.xci
# IP: The module: 'gt9147_init' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/gt9147_init/gt9147_init_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt9147_init'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/gt9147_init/gt9147_init.xci
# IP: The module: 'gt9147_init' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/gt9147_init/gt9147_init_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt9147_init'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
