# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/main_xbar/main_xbar.xci
# IP: The module: 'main_xbar' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/main_xbar/main_xbar_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_xbar'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/main_xbar/main_xbar.xci
# IP: The module: 'main_xbar' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/XF/Desktop/chiplabdemo/chiplab/IP/xilinx_ip/main_xbar/main_xbar_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_xbar'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
